export const CATEGORIES = {
  'status-check': {
    name: 'Verification & Status',
    nameHi: 'सत्यापन और स्थिति',
    description: 'Kist verification, beneficiary roster, FTO, eKYC, land seeding guides',
    descriptionHi: 'किस्त सत्यापन, लाभार्थी सूची, एफटीओ, ईकेवाईसी, भूमि सीडिंग गाइड',
    icon: '',
    color: 'blue',
  },
  'loan': {
    name: 'Credit & Loans',
    nameHi: 'ऋण और क्रेडिट',
    description: 'KCC loan, farm equipment loan, and bank credit guides',
    descriptionHi: 'केसीसी लोन, कृषि उपकरण ऋण, और बैंक क्रेडिट गाइड',
    icon: '💰',
    color: 'amber',
  },
  'farming': {
    name: 'Farming & Schemes',
    nameHi: 'खेती और योजनाएं',
    description: 'Soil analysis, crop insurance, AgriStack, Nano DAP and other schemes',
    descriptionHi: 'मृदा विश्लेषण, फसल बीमा, एग्रीस्टैक, नैनो डीएपी और अन्य योजनाएं',
    icon: '🌱',
    color: 'emerald',
  },
  'mandi': {
    name: 'Market Rates',
    nameHi: 'बाजार दरें',
    description: 'Daily vegetable and fruit market rates, wholesale prices',
    descriptionHi: 'दैनिक सब्जी और फल बाजार दरें, थोक कीमतें',
    icon: '',
    color: 'yellow',
  },
} as const;

export type CategorySlug = keyof typeof CATEGORIES;

export interface ArticleMeta {
  slug: string;
  title: string;
  desc: string;
  ogTitle: string;
  readonly keywords: readonly string[];
  component: string;
  category: CategorySlug;
  publishedTime: string;
  modifiedTime: string;
  readingTime?: number;
  author: string;
  authorBio?: string;
  states?: readonly string[];
  districts?: readonly string[];
  banks?: readonly string[];
  schemes?: readonly string[];
  ogImage?: string;
  relatedSlugs?: readonly string[];
}

export const ARTICLES: readonly ArticleMeta[] = [
  {
    slug: 'KisanRinKahaSeLe2026',
    title: 'Kisan Loan 2026: KCC, Bank, CSC Guide',
    desc: 'Loan chahiye to confusion hota hai — SBI, cooperative, CSC, har jagah process alag. Is guide mein sab kuch hai.',
    ogTitle: 'Kisan Loan Guide 2026 — Hindi Jankari',
    keywords: [
      'kisan loan kahan se milega 2026',
      'kisan credit card',
      'kisan loan 2026',
      'SBI kisan loan',
      'CSC center loan',
      'कृषि ऋण कहाँ से लें',
      'किसान लोन 2026',
    ],
    component: 'KisanRinKahaSeLe2026',
    category: 'loan',
    publishedTime: '2026-01-10T08:00:00+05:30',
    modifiedTime: '2026-01-10T08:00:00+05:30',
    readingTime: 8,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    banks: ['sbi', 'pnb', 'bob', 'cooperative'],
    schemes: ['kcc'],
    ogImage: '/images/kisan-rin-kaha-se-le-2026.webp',
    relatedSlugs: ['KisanCreditCardOnlineApply2026', 'KisanTractorLoan2026', 'PmKisanCscRegistrationCharges', 'PmKisanBankAccountChangeProcess', 'PmKisanMasterGuide2026'],
  },
  {
    slug: 'KisanTractorLoan2026',
    title: 'Tractor Loan 2026: Bina Down Payment?',
    desc: 'Bina down payment ke tractor loan possible hai? Mahindra Finance, TATA Capital aur state banks ki schemes, eligibility aur apply process — sab yahan.',
    ogTitle: 'Tractor Loan Bina Down Payment 2026',
    keywords: [
      'tractor loan 2026',
      'tractor finance 2026',
      'ट्रैक्टर लोन बिना डाउन पेमेंट',
      'किसान ट्रैक्टर लोन 2026',
    ],
    component: 'KisanTractorLoan2026',
    category: 'loan',
    publishedTime: '2026-01-20T08:00:00+05:30',
    modifiedTime: '2026-01-20T08:00:00+05:30',
    readingTime: 10,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    banks: ['mahindra-finance', 'tata-capital'],
    schemes: ['nabard-tractor'],
    ogImage: '/images/articles/kisan-tractor-loan-2026/hero-2.webp',
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanCreditCardOnlineApply2026', 'custom-hiring-centre-chc-portal', 'PmKusumYojanaSolarSubsidy2026', 'PmKisanMaandhanYojanaPension'],
  },
  {
    slug: 'PmKisanBeneficiaryList2026',
    title: 'PM Kisan Beneficiary List 2026: Check',
    desc: 'Beneficiary list mein naam check karo, gaon ki poori village wise list dekho, PDF download karo. 7 rejection reasons + fix bhi.',
    ogTitle: 'PM Kisan Beneficiary List 2026 Guide',
    keywords: [
      'pm kisan beneficiary list 2026',
      'pm kisan village wise roster',
      'pm kisan naam check karo',
      'पीएम किसान लाभार्थी सूची 2026',
      'pm kisan beneficiary list pdf download',
      'pm kisan gaon wise list',
    ],
    component: 'PmKisanBeneficiaryList2026',
    category: 'status-check',
    publishedTime: '2026-02-10T08:00:00+05:30',
    modifiedTime: '2026-02-10T08:00:00+05:30',
    readingTime: 15,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/pm-kisan-beneficiary-status-kisanstatus.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanMasterGuide2026', 'PmKisanVillageWiseListPdfDownload', 'PmKisanRejectedStatusReApplyGuide', 'pm-kisan-self-registered-status-check'],
  },
  {
    slug: 'PmKisanEkycOnline2026',
    title: 'PM Kisan eKYC 2026: 2 Min Mein Karein',
    desc: 'eKYC mandatory hai — bina iske PM Kisan kist nahi milegi. OTP ya CSC biometric se free mein 2 minute mein eKYC karne ka step-by-step tarika.',
    ogTitle: 'PM Kisan eKYC Online 2026 Guide',
    keywords: [
      'pm kisan ekyc online 2026',
      'pm kisan ekyc kaise kare',
      'ekyc otp verification',
      'csc biometric ekyc',
      'पीएम किसान ईकेवाईसी',
    ],
    component: 'PmKisanEkycOnline2026',
    category: 'status-check',
    publishedTime: '2026-03-15T08:00:00+05:30',
    modifiedTime: '2026-03-15T08:00:00+05:30',
    readingTime: 8,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-ekyc-online-2026/otp-vs-biometric.webp',
    relatedSlugs: ['PmKisanFaceAuthenticationEkyc', 'PmKisanMasterGuide2026', 'PmKisan24viKist2026', 'PmKisanCscRegistrationCharges', 'PmKisanMobileNumberChangeUpdate'],
  },
  {
    slug: 'PmfbyCropInsurance2026',
    title: 'PMFBY Crop Insurance 2026: 2% Premium',
    desc: 'Fasal kharab ho toh compensation milega. Kharif 2%, Rabi 1.5% premium. Enrollment deadline mat bhoolo.',
    ogTitle: 'PMFBY Crop Insurance 2026 Guide',
    keywords: [
      'pmfby crop insurance 2026',
      'fasal bima yojana',
      'crop insurance claim',
      'pmfby enrollment',
      'प्रधानमंत्री फसल बीमा योजना',
    ],
    component: 'PmfbyCropInsurance2026',
    category: 'farming',
    publishedTime: '2026-04-01T08:00:00+05:30',
    modifiedTime: '2026-04-01T08:00:00+05:30',
    readingTime: 10,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pmfby'],
    ogImage: '/images/articles/pmfby-crop-insurance-2026/hero-image.webp',
    relatedSlugs: ['PmKisanMaandhanYojanaPension', 'PmKusumYojanaSolarSubsidy2026', 'bakri-palan-yojana-nlm-subsidy', 'KisanCreditCardOnlineApply2026', 'soil-health-card-complete-guide-2026'],
  },
  {
    slug: 'KisanCreditCardOnlineApply2026',
    title: 'Kisan Credit Card 2026: ₹5 Lakh Loan',
    desc: 'KCC hai to ₹5 lakh tak ka loan sirf 4% interest par mil sakta hai. Online apply process, eligibility aur zaroori documents ki puri jankari yahan.',
    ogTitle: 'KCC Online Apply — ₹5 Lakh Loan 2026',
    keywords: [
      'kisan credit card online apply 2026',
      'KCC apply online',
      'किसान क्रेडिट कार्ड ऑनलाइन अप्लाई 2026',
    ],
    component: 'KisanCreditCardOnlineApply2026',
    category: 'loan',
    publishedTime: '2026-06-01T08:00:00+05:30',
    modifiedTime: '2026-06-01T08:00:00+05:30',
    readingTime: 9,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    banks: ['sbi', 'pnb', 'bob', 'cooperative'],
    schemes: ['kcc'],
    ogImage: '/images/kisan-credit-card-apply-online-hero.webp',
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanTractorLoan2026', 'PmKisanBankAccountChangeProcess', 'PmKusumYojanaSolarSubsidy2026', 'PmKisanMaandhanYojanaPension'],
  },
  {
    slug: 'pm-kisan-fto-generated-ka-matlab-kya-hai',
    title: 'FTO Generated Meaning: PM Kisan Status',
    desc: 'FTO Generated aur FTO Pending mein confused ho? FTO matlab Fund Transfer Order — iska matlab, status ke stages aur kist kab aayegi, sab samjhein.',
    ogTitle: 'FTO Generated Matlab — PM Kisan Guide',
    keywords: [
      'FTO generated meaning',
      'fund transfer order status',
      'एफटीओ जेनरेटेड क्या होता है',
    ],
    component: 'pm-kisan-fto-generated-ka-matlab-kya-hai',
    category: 'status-check',
    publishedTime: '2026-06-23T08:00:00+05:30',
    modifiedTime: '2026-06-23T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/pm-kisan-fto-generated-featured-image-kisanstatus.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanBeneficiaryList2026', 'PmKisanPaymentFailedFix2026', 'PmKisanBankAccountChangeProcess', 'PmKisanMasterGuide2026'],
  },
  {
    slug: 'NanoDap500mlPriceInIndia2026',
    title: 'Nano DAP 500ml Price 2026: IFFCO Rate',
    desc: 'IFFCO Nano DAP 500ml bottle ka price ₹280-320 ke beech hai. Latest rate, normal DAP se comparison aur kaha se sasta milega — puri jankari yahan.',
    ogTitle: 'Nano DAP 500ml Price 2026 India',
    keywords: [
      'Nano DAP 500ml price India 2026',
      'IFFCO Nano DAP price',
      'नैनो डीएपी 500ml कीमत 2026',
    ],
    component: 'NanoDap500mlPriceInIndia2026',
    category: 'farming',
    publishedTime: '2026-06-24T08:00:00+05:30',
    modifiedTime: '2026-06-24T08:00:00+05:30',
    readingTime: 7,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['nano-dap'],
    ogImage: '/images/nano-dap-500ml-bottle-hero.webp',
    relatedSlugs: ['soil-health-card-complete-guide-2026', 'AgriStackKyaHai2026', 'vermi-compost-business-guide', 'drip-sprinkler-irrigation-subsidy', 'PmKusumYojanaSolarSubsidy2026'],
  },
  {
    slug: 'PmKisan24viKist2026',
    title: 'PM Kisan 24vi Kist 2026: Date & Status',
    desc: '23vi kist aa gayi, ab 24vi ka intezaar. October 2026 tak aane ki umeed hai — release date, beneficiary status check aur latest update yahan dekhein.',
    ogTitle: 'PM Kisan 24vi Kist — Kab Aayegi?',
    keywords: [
      'pm kisan 24vi kist 2026',
      'next kist date 2026',
      'पीएम किसान 24वीं किस्त 2026',
    ],
    component: 'PmKisan24viKist2026',
    category: 'status-check',
    publishedTime: '2026-06-24T08:00:00+05:30',
    modifiedTime: '2026-06-24T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/pm-kisan-24vi-kist-october-2026.webp',
    relatedSlugs: ['PmKisan25viKist2027', 'PmKisanBeneficiaryList2026', 'pm-kisan-fto-generated-ka-matlab-kya-hai', 'PmKisanPaymentFailedFix2026', 'PmKisanMasterGuide2026'],
  },
  {
    slug: 'AgriStackKyaHai2026',
    title: 'AgriStack 2026: Digital Kisan ID Guide',
    desc: 'AgriStack ek digital kisan ID hai jo PM Kisan se connected hai. Iska matlab, fayde, registration process aur eligibility ki puri jankari yahan.',
    ogTitle: 'AgriStack Kya Hai — Kisan ID Guide',
    keywords: [
      'AgriStack kya hai',
      'AgriStack 2026',
      'digital kisan ID AgriStack',
      'एग्रीस्टैक क्या है',
    ],
    component: 'AgriStackKyaHai2026',
    category: 'farming',
    publishedTime: '2026-06-24T08:00:00+05:30',
    modifiedTime: '2026-06-24T08:00:00+05:30',
    readingTime: 10,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['agristack', 'pm-kisan'],
    ogImage: '/images/articles/agristack-kya-hai/infographic.webp',
    relatedSlugs: ['NanoDap500mlPriceInIndia2026', 'soil-health-card-complete-guide-2026', 'PmKisanMasterGuide2026', 'PmKisanBeneficiaryList2026', 'PmKisanEkycOnline2026'],
  },
  {
    slug: 'PmKisanMasterGuide2026',
    title: 'PM Kisan Complete Guide 2026: All Fixes',
    desc: 'PM Kisan ka har problem ek jagah — status verify, eKYC process, payment fail fix aur beneficiary list check karne ka complete step-by-step guide.',
    ogTitle: 'PM Kisan Complete Guide — Sab Fix',
    keywords: [
      'pm kisan complete guide 2026',
      'all problems solution',
      'पीएम किसान पूर्ण गाइड',
    ],
    component: 'PmKisanMasterGuide2026',
    category: 'status-check',
    publishedTime: '2026-06-27T08:00:00+05:30',
    modifiedTime: '2026-06-27T08:00:00+05:30',
    readingTime: 15,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-complete-guide/hero.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanBeneficiaryList2026', 'PmKisanEkycOnline2026', 'PmKisanPaymentFailedFix2026', 'PmKisanCorrectionForm2026'],
  },
  {
    slug: 'soil-health-card-complete-guide-2026',
    title: 'Soil Health Card 2026: Mitti Test Guide',
    desc: 'Mitti test karwao aur sahi khaad chuno — CSC se form lo, sample do aur 15 din mein report pao. Soil Health Card banwane ka complete guide yahan.',
    ogTitle: 'Soil Health Card 2026 — Puri Jankari',
    keywords: [
      'soil health card complete guide 2026',
      'soil health card download',
      'मिट्टी स्वास्थ्य कार्ड 2026',
    ],
    component: 'soil-health-card-complete-guide-2026',
    category: 'farming',
    publishedTime: '2026-06-27T08:00:00+05:30',
    modifiedTime: '2026-06-27T08:00:00+05:30',
    readingTime: 8,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['soil-health-card'],
    ogImage: '/images/articles/soil-health-card-complete-guide-2026/hero.webp',
    relatedSlugs: ['NanoDap500mlPriceInIndia2026', 'AgriStackKyaHai2026', 'vermi-compost-business-guide', 'drip-sprinkler-irrigation-subsidy', 'PmKusumYojanaSolarSubsidy2026'],
  },
  {
    slug: 'mandi-bhav-today',
    title: 'Aaj Ka Mandi Bhav: Daily Sabzi Rates',
    desc: 'Aaj ka mandi bhav — aloo ₹20-24, pyaaz ₹26-30, tamatar ₹38-45. Sabzi aur anaj ke daily updated rates apne sheher ke hisaab se yahan dekhein.',
    ogTitle: 'Aaj Ka Mandi Bhav — Live Rates',
    keywords: [
      'aaj ka mandi bhav',
      'mandi bhav today hindi',
      'aaj ke sabzi bhav',
    ],
    component: 'mandi-bhav-today',
    category: 'mandi',
    publishedTime: '2026-06-30T09:30:00+05:30',
    modifiedTime: '2026-06-30T09:30:00+05:30',
    readingTime: 5,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    ogImage: '/images/articles/mandi-bhav-today/mandi-fresh-vegetables-mixed.webp',
    relatedSlugs: ['PmKisanMasterGuide2026', 'PmKisan24viKist2026', 'PmKisanBeneficiaryList2026', 'KisanRinKahaSeLe2026', 'PmKisanMaandhanYojanaPension'],
  },
  {
    slug: 'PmKisanPaymentFailedFix2026',
    title: 'PM Kisan Payment Failed 2026: 7 Fixes',
    desc: 'Payment failed dikh raha hai? Aadhaar seeding, IFSC, dormant account — 7 wajah aur turant fix ka tarika. Arrears bhi milenge.',
    ogTitle: 'PM Kisan Payment Failed Fix 2026',
    keywords: [
      'pm kisan payment failed',
      'payment fail fix',
      'aadhaar seeding dbt',
      'pm kisan paisa nahi aaya',
      'payment rejected fix',
      'पीएम किसान पेमेंट फेल',
    ],
    component: 'PmKisanPaymentFailedFix2026',
    category: 'status-check',
    publishedTime: '2026-07-06T08:00:00+05:30',
    modifiedTime: '2026-07-06T08:00:00+05:30',
    readingTime: 9,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-payment-failed-fix-2026/payment-failed-hero.webp',
    relatedSlugs: ['pm-kisan-fto-generated-ka-matlab-kya-hai', 'PmKisanMasterGuide2026', 'PmKisan24viKist2026', 'PmKisanBankAccountChangeProcess', 'PmKisanCorrectionForm2026'],
  },
  {
    slug: 'PmKisan25viKist2027',
    title: 'PM Kisan 25vi Kist 2027: Date & Amount',
    desc: '25vi kist expected Feb-Mar 2027 mein. ₹2,000 confirmed, increase possible. Abhi se eKYC, bank seeding, land records perfect karo.',
    ogTitle: 'PM Kisan 25vi Kist 2027 Guide',
    keywords: [
      'pm kisan 25vi kist 2027',
      '25vi kist kab aayegi',
      'pm kisan next installment',
      '25vi kist amount',
      'pm kisan feb 2027',
      'पीएम किसान 25वीं किस्त 2027',
    ],
    component: 'PmKisan25viKist2027',
    category: 'status-check',
    publishedTime: '2026-07-06T08:00:00+05:30',
    modifiedTime: '2026-07-06T08:00:00+05:30',
    readingTime: 8,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-25vi-kist-2027/hero-25vi-kist.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanBeneficiaryList2026', 'PmKisanPaymentFailedFix2026'],
  },
  {
    slug: 'pm-kisan-self-registered-status-check',
    title: 'PM Kisan Self Reg Status 2026: Check',
    desc: 'Self-registration karke bhool gaye? 7-10 din baad status check karna zaroori hai. Step-by-step guide + common problems + fix.',
    ogTitle: 'PM Kisan Self Registration Status',
    keywords: [
      'pm kisan self registration status check',
      'pm kisan self registered status',
      'pm kisan registration approval check',
      'self registration pending',
      'pm kisan status ghar baithe',
      'पीएम किसान सेल्फ रजिस्ट्रेशन स्टेटस',
    ],
    component: 'PmKisanSelfRegisteredStatusCheck',
    category: 'status-check',
    publishedTime: '2026-01-15T08:00:00+05:30',
    modifiedTime: '2026-07-07T08:00:00+05:30',
    readingTime: 10,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-self-registered-status-check/hero.webp',
    relatedSlugs: ['PmKisanBeneficiaryList2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanRejectedStatusReApplyGuide', 'PmKisanVoluntarySurrenderGuide'],
  },
  {
    slug: 'PmKisanCorrectionForm2026',
    title: 'PM Kisan Correction Form 2026: Fix Guide',
    desc: 'Naam spelling galat, bank IFSC mismatch, Aadhaar seeding error? PM Kisan correction form bharne ka step-by-step tarika — portal se aur CSC dono. Ruki hui kist wapas milegi.',
    ogTitle: 'PM Kisan Correction Form 2026 Guide',
    keywords: [
      'pm kisan correction form 2026',
      'pm kisan naam correction online',
      'pm kisan bank account update',
      'pm kisan aadhaar seeding error fix',
      'pm kisan correction status check',
      'pm kisan CSC se correction',
      'pm kisan name spelling mistake fix',
      'pm kisan mobile number change',
    ],
    component: 'PmKisanCorrectionForm2026',
    category: 'status-check',
    publishedTime: '2026-07-08T08:00:00+05:30',
    modifiedTime: '2026-07-08T08:00:00+05:30',
    readingTime: 8,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-correction-form-2026/pm-kisan-correction-hero.webp',
    relatedSlugs: ['PmKisanPaymentFailedFix2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisan24viKist2026', 'PmKisanBankAccountChangeProcess'],
  },
  {
    slug: 'PmKusumYojanaSolarSubsidy2026',
    title: 'PM Kusum Solar Pump 2026: 60% Subsidy',
    desc: 'Diesel pump band karo, solar pump lagao. 60% subsidy, zero bijli bill, 25 saal free paani. Eligibility, online apply, state-wise process, documents — sab kuch simple bhasha mein.',
    ogTitle: 'PM Kusum Solar Subsidy 2026 Guide',
    keywords: [
      'pm kusum yojana solar pump subsidy',
      'pm kusum yojana online apply 2026',
      'pm kusum yojana registration form',
      'solar pump subsidy apply kisan',
      'pm kusum yojana status check',
      'pm kusum yojana eligibility',
    ],
    component: 'PmKusumYojanaSolarSubsidy2026',
    category: 'farming',
    publishedTime: '2026-07-08T10:00:00+05:30',
    modifiedTime: '2026-07-08T10:00:00+05:30',
    readingTime: 12,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kusum'],
    ogImage: '/images/articles/pm-kusum-yojana-solar-subsidy-2026/solar-pump-hero.webp',
    relatedSlugs: ['drip-sprinkler-irrigation-subsidy', 'KisanCreditCardOnlineApply2026', 'KisanTractorLoan2026', 'PmKisanMasterGuide2026', 'soil-health-card-complete-guide-2026'],
  },
  {
    slug: 'PmKisanLandSeedingForm',
    title: 'PM Kisan Land Seeding Form 2026: PDF',
    desc: 'Land seeding form download karo — UP, Bihar, MP, Rajasthan ke state wise forms. Khasra-Khatauni details ke saath complete guide.',
    ogTitle: 'PM Kisan Land Seeding Form PDF',
    keywords: [
      'pm kisan land seeding form pdf download',
      'land seeding form state wise',
      'pm kisan khasra khatauni form',
      'pm kisan land seeding form kaise bhare',
      'land seeding no kaise fix kare',
      'pm kisan khasra number kaise dale',
    ],
    component: 'PmKisanLandSeedingForm',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 12,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-land-seeding-form/land-seeding-form-hero.webp',
    relatedSlugs: ['PmKisanBeneficiaryList2026', 'PmKisanEkycOnline2026', 'PmKisanMasterGuide2026', 'PmKisanCorrectionForm2026', 'PmKisanVillageWiseListPdfDownload'],
  },
  {
    slug: 'PmKisanFaceAuthenticationEkyc',
    title: 'PM Kisan Face Auth eKYC: Bina OTP',
    desc: 'OTP nahi aa raha? PM Kisan app se face authentication karke bina OTP ke eKYC complete karo. Step-by-step guide + common errors fix.',
    ogTitle: 'PM Kisan Face Auth eKYC Guide',
    keywords: [
      'pm kisan face authentication kyc',
      'pm kisan app bina otp kyc',
      'pmkisan goi app download',
      'face recognition pm kisan',
      'pm kisan mobile app ekyc',
      'bina otp pm kisan verification',
    ],
    component: 'PmKisanFaceAuthenticationEkyc',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 10,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-face-authentication-ekyc/face-auth-hero.webp',
    relatedSlugs: ['PmKisanEkycOnline2026', 'PmKisanMasterGuide2026', 'PmKisanPaymentFailedFix2026', 'PmKisanCscRegistrationCharges', 'PmKisanMobileNumberChangeUpdate'],
  },
  {
    slug: 'PmKisanVoluntarySurrenderGuide',
    title: 'PM Kisan Surrender Guide: Kaise Hatte?',
    desc: 'Government employee ya income tax filer ho? Galti se PM Kisan mein register ho gaye toh voluntary surrender kaise karein. Online + offline process.',
    ogTitle: 'PM Kisan Voluntary Surrender Guide',
    keywords: [
      'pm kisan voluntary surrender',
      'pm kisan benefit surrender form',
      'pm kisan se kaise haten',
      'income tax filer pm kisan surrender',
      'pm kisan government employee surrender',
      'pm kisan cancel registration',
    ],
    component: 'PmKisanVoluntarySurrenderGuide',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 12,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-voluntary-surrender/surrender-hero.webp',
    relatedSlugs: ['PmKisanMasterGuide2026', 'PmKisanCorrectionForm2026', 'PmKisanBeneficiaryList2026', 'pm-kisan-self-registered-status-check', 'PmKisanRejectedStatusReApplyGuide'],
  },
  {
    slug: 'PmKisanStateNodalOfficerList',
    title: 'PM Kisan Nodal Officer List: Contacts',
    desc: '155261 se kaam nahi ban raha? Har state ke nodal officer ka email, phone number aur address. Email template + grievance portal guide.',
    ogTitle: 'PM Kisan Nodal Officer Contact List',
    keywords: [
      'pm kisan state nodal officer list',
      'pm kisan district officer contact',
      'pm kisan complaint officer',
      'pm kisan grievance officer number',
      'pm kisan helpline state wise',
      'pm kisan district agriculture officer',
    ],
    component: 'PmKisanStateNodalOfficerList',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 18,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-state-nodal-officer-list/officer-hero.webp',
    relatedSlugs: ['PmKisanPaymentFailedFix2026', 'PmKisanMasterGuide2026', 'PmKisanBeneficiaryList2026', 'PmKisanCorrectionForm2026', 'PmKisanCscRegistrationCharges'],
  },
  {
    slug: 'PmKisanBankAccountChangeProcess',
    title: 'PM Kisan Bank Change 2026: Naya Account',
    desc: 'Purana account band ho gaya? CSC ya BAO office jakar naya bank account kaise link karein. NPCI seeding + IFSC update ka pura tarika.',
    ogTitle: 'PM Kisan Bank Account Change Guide',
    keywords: [
      'pm kisan bank account change kaise kare',
      'pm kisan new bank account link',
      'pm kisan bank details update',
      'pm kisan bank change csc',
      'pm kisan bank account update online',
      'pm kisan bank change form',
    ],
    component: 'PmKisanBankAccountChangeProcess',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 16,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-bank-account-change/bank-change-hero.webp',
    relatedSlugs: ['PmKisanPaymentFailedFix2026', 'pm-kisan-fto-generated-ka-matlab-kya-hai', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanCscRegistrationCharges'],
  },
  {
    slug: 'PmKisanCscRegistrationCharges',
    title: 'PM Kisan CSC Charges 2026: Sahi Fees',
    desc: 'CSC wala ₹500 maang raha hai? Sarkari rate sirf ₹25-30 hai. Sahi fees, free online method, aur fraud se bachne ka tarika.',
    ogTitle: 'PM Kisan CSC Registration Charges',
    keywords: [
      'pm kisan csc registration fees',
      'pm kisan csc se kaise kare',
      'csc pm kisan charges',
      'pm kisan csc center cost',
      'pm kisan csc kitne paise leta hai',
      'pm kisan csc registration process',
    ],
    component: 'PmKisanCscRegistrationCharges',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 14,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-csc-registration-charges/csc-registration-hero.webp',
    relatedSlugs: ['PmKisanEkycOnline2026', 'PmKisanMasterGuide2026', 'PmKisanBankAccountChangeProcess', 'PmKisanStateNodalOfficerList', 'PmKisanMobileNumberChangeUpdate'],
  },
  {
    slug: 'PmKisanMaandhanYojanaPension',
    title: 'PM Kisan Maandhan 2026: ₹3000 Pension',
    desc: 'Chhote kisanon ke liye pension scheme. 18-40 saal ki umar mein join karo, 60 ke baad ₹3000 har mahine pao. Contribution table + apply process.',
    ogTitle: 'PM Kisan Maandhan Yojana Guide',
    keywords: [
      'pm kisan maandhan yojana',
      'kisan pension yojana eligibility',
      'pm kmy pension apply',
      'pm kisan pension 3000',
      'pm kisan maan dhan yojana form',
      'pm kisan pension yojana apply online',
    ],
    component: 'PmKisanMaandhanYojanaPension',
    category: 'farming',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 16,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan', 'pm-kmy'],
    ogImage: '/images/articles/pm-kisan-maandhan-yojana-pension/maandhan-hero.webp',
    relatedSlugs: ['PmKisanMasterGuide2026', 'PmKisanBeneficiaryList2026', 'PmKisanEkycOnline2026', 'PmfbyCropInsurance2026', 'bakri-palan-yojana-nlm-subsidy'],
  },
  {
    slug: 'PmKisanRejectedStatusReApplyGuide',
    title: 'PM Kisan Rejected Status 2026: Reapply',
    desc: 'Status rejected dikh raha hai? 7 main reasons + step-by-step re-application guide. CSC correction form + arrears claim process.',
    ogTitle: 'PM Kisan Rejected Status Fix Guide',
    keywords: [
      'pm kisan rejected status fix',
      'pm kisan reapply kaise kare',
      'pm kisan rejection reason',
      'pm kisan rejected list solution',
      'pm kisan application rejected kya kare',
      'pm kisan rejected name list',
    ],
    component: 'PmKisanRejectedStatusReApplyGuide',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 17,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-rejected-status-re-apply-guide/rejected-status-hero.webp',
    relatedSlugs: ['PmKisanBeneficiaryList2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanCorrectionForm2026', 'pm-kisan-self-registered-status-check'],
  },
  {
    slug: 'PmKisanVillageWiseListPdfDownload',
    title: 'PM Kisan Village List 2026: PDF Download',
    desc: 'Apne gaon ki puri PM Kisan beneficiary list PDF mein download karo. Mobile + PC dono tarika. Excel convert trick + state portals.',
    ogTitle: 'PM Kisan Village Wise List PDF',
    keywords: [
      'pm kisan village wise list pdf',
      'pm kisan gaon wise list download',
      'pm kisan pdf roster',
      'pm kisan village list kaise dekhe',
      'pm kisan gaon ki list',
      'pm kisan village wise beneficiary list',
    ],
    component: 'PmKisanVillageWiseListPdfDownload',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 15,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-village-wise-list-pdf-download/village-list-hero.webp',
    relatedSlugs: ['PmKisanBeneficiaryList2026', 'PmKisanRejectedStatusReApplyGuide', 'PmKisanMasterGuide2026', 'PmKisanStateNodalOfficerList', 'PmKisanLandSeedingForm'],
  },
  {
    slug: 'PmKisanMobileNumberChangeUpdate',
    title: 'PM Kisan Mobile Change 2026: Naya SIM',
    desc: 'Purana SIM band hai aur OTP nahi aa raha? CSC ya BAO office jakar naya mobile number kaise link karein. Online vs offline complete guide.',
    ogTitle: 'PM Kisan Mobile Number Change Guide',
    keywords: [
      'pm kisan mobile number change',
      'pm kisan mobile number update',
      'pm kisan sim change kaise kare',
      'pm kisan bina purane sim mobile update',
      'pm kisan mobile number update csc',
      'pm kisan mobile number change online',
    ],
    component: 'PmKisanMobileNumberChangeUpdate',
    category: 'status-check',
    publishedTime: '2026-07-10T08:00:00+05:30',
    modifiedTime: '2026-07-10T08:00:00+05:30',
    readingTime: 15,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-mobile-number-change-update/mobile-change-hero.webp',
    relatedSlugs: ['PmKisanCscRegistrationCharges', 'PmKisanEkycOnline2026', 'PmKisanMasterGuide2026', 'PmKisanRejectedStatusReApplyGuide', 'PmKisanFaceAuthenticationEkyc'],
  },
  {
    slug: 'bakri-palan-yojana-nlm-subsidy',
    title: 'Bakri Palan Yojana 2026: NLM Subsidy',
    desc: 'National Livestock Mission se 50% subsidy, 20 bakri farm ka complete budget, 5-year profit projection, aur real risks jo koi nahi batata.',
    ogTitle: 'Bakri Palan Yojana 2026 Guide',
    keywords: [
      'bakri palan yojana 2026',
      'nlm subsidy goat farming',
      'bakri palan subsidy kaise milegi',
      'bakri palan profit kitna hota hai',
      'goat farming loan process',
      'bakri palan nasl kaunsi chunein',
    ],
    component: 'BakriPalanYojana',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 18,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['nlm', 'pm-kisan'],
    ogImage: '/images/kisanguides/bakri-palan-nlm-subsidy.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'PmfbyCropInsurance2026', 'mushroom-kheti-nhb-subsidy'],
  },
  {
    slug: 'mushroom-kheti-nhb-subsidy',
    title: 'Mushroom Kheti 2026: NHB Subsidy Guide',
    desc: 'Oyster mushroom farming se mahine ka ₹40,000+ kamayein. 100-bag unit ka complete budget, NHB subsidy, aur step-by-step cultivation process.',
    ogTitle: 'Mushroom Kheti 2026 — Profit Guide',
    keywords: [
      'mushroom kheti 2026',
      'oyster mushroom farming subsidy',
      'mushroom kheti kaise shuru karein',
      'mushroom farming profit kitna hota hai',
      'nhb subsidy mushroom',
      'mushroom cultivation process',
    ],
    component: 'MushroomKheti',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 16,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['nhb', 'pm-fme'],
    ogImage: '/images/kisanguides/harvesting-mushroom.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'bakri-palan-yojana-nlm-subsidy', 'madhumakhi-palan-kvic-subsidy'],
  },
  {
    slug: 'madhumakhi-palan-kvic-subsidy',
    title: 'Madhumakhi Palan 2026: KVIC Subsidy',
    desc: 'Beekeeping se dohri kamai - shahad + pollination. 50-box unit ka budget, KVIC subsidy 80% tak, aur real profit calculation.',
    ogTitle: 'Madhumakhi Palan 2026 Guide',
    keywords: [
      'madhumakhi palan 2026',
      'beekeeping subsidy kvic',
      'madhumakhi palan kaise shuru karein',
      'madhumakhi palan profit kitna hota hai',
      'honey bee farming subsidy',
      'madhumakhi palan cost breakdown',
    ],
    component: 'MadhumakhiPalan',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 17,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['kvic', 'nhb', 'pm-fme'],
    ogImage: '/images/kisanguides/madhumakhi-palan-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'mushroom-kheti-nhb-subsidy', 'pm-matsya-sampada-yojana-fish-farming'],
  },
  {
    slug: 'pm-matsya-sampada-yojana-fish-farming',
    title: 'PM Matsya Yojana 2026: 60% Subsidy',
    desc: 'Fish farming par 40-60% subsidy. 1 acre pond ka complete budget, Biofloc vs Traditional, aur 3-year profit projection.',
    ogTitle: 'PM Matsya Sampada Yojana 2026',
    keywords: [
      'pm matsya sampada yojana 2026',
      'fish farming subsidy 60 percent',
      'machli palan kaise shuru karein',
      'fish farming profit kitna hota hai',
      'biofloc technology fish farming',
      'pmmsy subsidy eligibility',
    ],
    component: 'PMatsyaSampada',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 18,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pmmsy', 'pm-kisan'],
    ogImage: '/images/kisanguides/fish-farming-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'madhumakhi-palan-kvic-subsidy', 'silage-making-business-guide'],
  },
  {
    slug: 'silage-making-business-guide',
    title: 'Silage Business 2026: SMAM Subsidy',
    desc: 'Silage business se mahine ka ₹50,000+ kamayein. 100-bag unit ka complete budget, SMAM subsidy, aur real profit calculation.',
    ogTitle: 'Silage Making Business 2026 Guide',
    keywords: [
      'silage making business 2026',
      'silage business profit kitna hota hai',
      'silage making kaise shuru karein',
      'silage business cost breakdown',
      'smam subsidy silage making',
      'silage business risk aur challenges',
    ],
    component: 'SilageMaking',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 16,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['smam', 'aif', 'pm-fme'],
    ogImage: '/images/kisanguides/silage-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'pm-matsya-sampada-yojana-fish-farming', 'custom-hiring-centre-chc-portal'],
  },
  {
    slug: 'pm-fme-yojana-food-processing',
    title: 'PM FME Yojana 2026: 35% Subsidy',
    desc: 'PM FME se 35% subsidy (max ₹10 lakh). Achar, papad, bakery units ke liye. ODOP benefits, application process, aur documents checklist.',
    ogTitle: 'PM FME Yojana 2026 Food Subsidy',
    keywords: [
      'pm fme yojana 2026',
      'pm fme subsidy 35 percent',
      'pm fme kaise apply karein',
      'pm fme eligibility criteria',
      'pm fme odop scheme',
      'pm fme food processing subsidy',
    ],
    component: 'PMFMEYojana',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 15,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pm-fme', 'pmegp'],
    ogImage: '/images/kisanguides/pmfhero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'vermi-compost-business-guide', 'mushroom-kheti-nhb-subsidy'],
  },
  {
    slug: 'custom-hiring-centre-chc-portal',
    title: 'Custom Hiring Centre 2026: SMAM Guide',
    desc: 'CHC khol kar machinery rent se kamayein. SMAM subsidy 40-50%, 8 implements ka complete budget, aur real profit calculation.',
    ogTitle: 'Custom Hiring Centre 2026 Guide',
    keywords: [
      'custom hiring centre 2026',
      'chc portal registration',
      'chc business profit kitna hota hai',
      'smam subsidy farm machinery',
      'chc kaise shuru karein',
      'chc business cost breakdown',
    ],
    component: 'CHCPortal',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 17,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['smam', 'pm-kisan'],
    ogImage: '/images/kisanguides/chc-portal-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanTractorLoan2026', 'KisanCreditCardOnlineApply2026', 'silage-making-business-guide', 'PmKisanMaandhanYojanaPension'],
  },
  {
    slug: 'vermi-compost-business-guide',
    title: 'Vermi Compost Business 2026: PKVY Guide',
    desc: 'Vermi compost business se organic fertilizer bechein. PKVY subsidy 50-75%, 10-pit unit ka budget, aur real profit calculation.',
    ogTitle: 'Vermi Compost Business 2026 Guide',
    keywords: [
      'vermi compost business 2026',
      'vermi compost kaise banayein',
      'vermi compost profit kitna hota hai',
      'vermi compost subsidy pkvy',
      'vermi compost business cost breakdown',
      'vermi compost risk aur challenges',
    ],
    component: 'VerminCompost',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 16,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pkvy', 'pm-fme'],
    ogImage: '/images/kisanguides/vermi-compost-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'soil-health-card-complete-guide-2026', 'NanoDap500mlPriceInIndia2026', 'pm-fme-yojana-food-processing'],
  },
  {
    slug: 'drip-sprinkler-irrigation-subsidy',
    title: 'Drip Irrigation Subsidy 2026: 75% Off',
    desc: 'Micro-irrigation par 55-75% subsidy. Drip vs Sprinkler comparison, PMKSY application process, aur real savings calculation.',
    ogTitle: 'Drip Sprinkler Subsidy 2026 Guide',
    keywords: [
      'drip irrigation subsidy 2026',
      'sprinkler irrigation subsidy',
      'pmksy per drop more crop',
      'drip vs sprinkler kaunsa behtar',
      'micro irrigation subsidy 75 percent',
      'drip irrigation kaise lagwayein',
    ],
    component: 'DripSprinkler',
    category: 'farming',
    publishedTime: '2026-07-11T08:00:00+05:30',
    modifiedTime: '2026-07-11T08:00:00+05:30',
    readingTime: 15,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['pmksy', 'pm-kusum'],
    ogImage: '/images/kisanguides/drip-sprinkler-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'soil-health-card-complete-guide-2026', 'NanoDap500mlPriceInIndia2026', 'PmKisanMaandhanYojanaPension'],
  },
] as const;

export const ARTICLES_MAP: Readonly<Record<string, ArticleMeta>> = Object.freeze(
  Object.fromEntries(ARTICLES.map((a) => [a.slug, a]))
);

export function getArticleBySlug(slug: string): ArticleMeta | undefined {
  return ARTICLES_MAP[slug];
}

export function getArticlesByCategory(category: CategorySlug): readonly ArticleMeta[] {
  return ARTICLES.filter((a) => a.category === category);
}

export function getLatestArticles(limit: number = 5): readonly ArticleMeta[] {
  return [...ARTICLES]
    .sort((a, b) => new Date(b.publishedTime).getTime() - new Date(a.publishedTime).getTime())
    .slice(0, limit);
}

export function getArticlesByKeyword(keyword: string): readonly ArticleMeta[] {
  const lower = keyword.toLowerCase();
  return ARTICLES.filter(
    (a) =>
      a.keywords.some((k) => k.toLowerCase().includes(lower)) ||
      a.title.toLowerCase().includes(lower) ||
      a.desc.toLowerCase().includes(lower)
  );
}

export function getCategoryInfo(category: CategorySlug) {
  return CATEGORIES[category];
}

export function getAllCategories(): readonly CategorySlug[] {
  return Object.keys(CATEGORIES) as CategorySlug[];
}

export function getArticleCount(): number {
  return ARTICLES.length;
}

export function getRelatedArticles(slug: string, limit: number = 3): readonly ArticleMeta[] {
  const current = getArticleBySlug(slug);
  if (!current) return [];

  if (current.relatedSlugs && current.relatedSlugs.length > 0) {
    const explicit = current.relatedSlugs
      .map((s) => ARTICLES_MAP[s])
      .filter(Boolean) as ArticleMeta[];
    if (explicit.length >= limit) return explicit.slice(0, limit);

    const remaining = ARTICLES.filter(
      (a) => a.slug !== slug && a.category === current.category && !current.relatedSlugs?.includes(a.slug)
    );
    return [...explicit, ...remaining].slice(0, limit);
  }

  return ARTICLES.filter((a) => a.slug !== slug && a.category === current.category).slice(0, limit);
}

export function getReadingTime(slug: string): string {
  const mins = getArticleBySlug(slug)?.readingTime;
  return mins ? `${mins} min read` : '5 min read';
}

export function getArticlesByScheme(scheme: string): readonly ArticleMeta[] {
  return ARTICLES.filter((a) => a.schemes?.includes(scheme));
}

export function getArticlesByBank(bank: string): readonly ArticleMeta[] {
  return ARTICLES.filter((a) => a.banks?.includes(bank));
}

export function getArticlesByState(state: string): readonly ArticleMeta[] {
  return ARTICLES.filter((a) => a.states?.includes(state));
}

export function getAllSchemes(): readonly string[] {
  const set = new Set<string>();
  ARTICLES.forEach((a) => a.schemes?.forEach((s) => set.add(s)));
  return Array.from(set).sort();
}

export function getAllBanks(): readonly string[] {
  const set = new Set<string>();
  ARTICLES.forEach((a) => a.banks?.forEach((b) => set.add(b)));
  return Array.from(set).sort();
}

export function getAllStates(): readonly string[] {
  const set = new Set<string>();
  ARTICLES.forEach((a) => a.states?.forEach((s) => set.add(s)));
  return Array.from(set).sort();
}