{
    slug: 'pm-kisan-self-registered-status-check',
    title: 'PM Kisan Self Registration Status Check 2026: Ghar Baithe Jaano — Approved Hua Ya Nahi',
    desc: 'Self-registration karke bhool gaye? 7-10 din baad status check karna zaroori hai. Step-by-step guide + common problems + fix.',
    ogTitle: 'PM Kisan Self Registration Status Check 2026 — Complete Guide',
    keywords: ['pm kisan self registration status check', 'pm kisan self registered status', 'pm kisan registration approval check', 'self registration pending', 'pm kisan status ghar baithe', 'पीएम किसान सेल्फ रजिस्ट्रेशन स्टेटस'],
    component: 'PmKisanSelfRegisteredStatusCheck',
    category: 'status-check',
    publishedTime: '2026-01-15T08:00:00+05:30',
    modifiedTime: '2026-07-07T08:00:00+05:30',
    readingTime: 10,
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-complete-guide/hero.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanMasterGuide2026', 'PmKisanBeneficiaryList2026', 'pm-kisan-fto-generated-ka-matlab-kya-hai'],
  },