import type { ArticleMeta } from './categories';
import { AUTHOR_NAME } from '@/lib/site-config';
import { getAuthorBio } from '@/lib/author-bios';

export const CORE_ARTICLES: readonly ArticleMeta[] = [
  {
    slug: 'KisanRinKahaSeLe2026',
    title: 'Kisan Loan 2026: KCC, Bank, CSC Guide',
    desc: 'Loan chahiye to confusion hota hai — SBI, cooperative, CSC, har jagah process alag. Is guide mein sab kuch hai.',
    seoTitle: 'Kisan Rin Kaha Se Le 2026 — KCC, Bank, CSC',
    ogTitle: 'Kisan Loan Guide 2026 — Hindi Jankari',
    keywords: [
      'kisan loan kahan se milega 2026',
      'kisan credit card',
      'kisan loan 2026',
      'SBI kisan loan',
      'CSC center loan',
      'कृषि ऋण कहाँ से लें',
      'किसान लोन 2026',
    ],
    component: 'KisanRinKahaSeLe2026',
    category: 'loan',
    publishedTime: '2026-06-20T06:39:52+05:30',
    modifiedTime: '2026-08-18T19:30:00+05:30',
    readingTime: 8,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('KisanRinKahaSeLe2026'),
    banks: ['sbi', 'pnb', 'bob', 'cooperative'],
    schemes: ['kcc'],
    ogImage: '/images/kisan-rin-kaha-se-le-2026.webp',
    relatedSlugs: ['KisanCreditCardOnlineApply2026', 'KisanTractorLoan2026', 'PmKisanCscRegistrationCharges', 'PmKisanBankAccountChangeProcess', 'PmKisanMasterGuide2026'],
  },
  {
    slug: 'KisanTractorLoan2026',
    title: 'Tractor Loan 2026: Bina Down Payment?',
    desc: 'Bina down payment ke tractor loan possible hai? Mahindra Finance, TATA Capital aur state banks ki schemes, eligibility aur apply process — sab yahan.',
    ogTitle: 'Tractor Loan Bina Down Payment 2026',
    keywords: [
      'tractor loan 2026',
      'tractor finance 2026',
      'ट्रैक्टर लोन बिना डाउन पेमेंट',
      'किसान ट्रैक्टर लोन 2026',
    ],
    component: 'KisanTractorLoan2026',
    category: 'loan',
    publishedTime: '2026-06-20T06:39:52+05:30',
    modifiedTime: '2026-08-20T23:00:00+05:30',
    readingTime: 10,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('KisanTractorLoan2026'),
    banks: ['mahindra-finance', 'tata-capital'],
    schemes: ['nabard-tractor'],
    ogImage: '/images/articles/kisan-tractor-loan-2026/hero-2.webp',
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanCreditCardOnlineApply2026', 'custom-hiring-centre-chc-portal', 'PmKusumYojanaSolarSubsidy2026', 'PmKisanMaandhanYojanaPension'],
  },
  {
    slug: 'PmKisanBeneficiaryList2026',
    title: 'PM Kisan Beneficiary List 2026: Check',
    desc: 'State verification aam taur par 2-4 hafte me clear hota hai — nahi hua to Block Agriculture Officer se milein. Beneficiary list me naam aur 7 fixes yahan.',
    ogTitle: 'PM Kisan Beneficiary List 2026 Guide',
    keywords: [
      'pm kisan beneficiary list 2026',
      'pm kisan village wise roster',
      'pm kisan naam check karo',
      'पीएम किसान लाभार्थी सूची 2026',
      'pm kisan gaon wise list',
    ],
    component: 'PmKisanBeneficiaryList2026',
    category: 'status-check',
    publishedTime: '2026-06-20T06:39:52+05:30',
    modifiedTime: '2026-08-18T20:00:00+05:30',
    readingTime: 15,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanBeneficiaryList2026'),
    schemes: ['pm-kisan'],
    ogImage: '/images/pm-kisan-beneficiary-status-kisanstatus.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanMasterGuide2026', 'PmKisanVillageWiseListPdfDownload', 'PmKisanRejectedStatusReApplyGuide', 'pm-kisan-self-registered-status-check'],
  },
  {
    slug: 'PmKisanEkycOnline2026',
    title: 'PM Kisan eKYC 2026: 2 Min Mein Karein',
    seoTitle: 'PM Kisan eKYC 2026 — OTP, Biometric, Face Auth',
    desc: 'eKYC mandatory hai — bina iske PM Kisan kist nahi milegi. OTP ya CSC biometric se free mein 2 minute mein eKYC karne ka step-by-step tarika.',
    ogTitle: 'PM Kisan eKYC Online 2026 Guide',
    keywords: [
      'pm kisan ekyc online 2026',
      'pm kisan ekyc kaise kare',
      'ekyc otp verification',
      'csc biometric ekyc',
      'पीएम किसान ईकेवाईसी',
    ],
    component: 'PmKisanEkycOnline2026',
    category: 'status-check',
    publishedTime: '2026-06-20T06:39:52+05:30',
    modifiedTime: '2026-08-18T20:00:00+05:30',
    readingTime: 8,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanEkycOnline2026'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-ekyc-online-2026/otp-vs-biometric.webp',
    relatedSlugs: ['PmKisanFaceAuthenticationEkyc', 'PmKisanMasterGuide2026', 'PmKisan24viKist2026', 'PmKisanCscRegistrationCharges', 'PmKisanMobileNumberChangeUpdate'],
  },
  {
    slug: 'PmfbyCropInsurance2026',
    title: 'PMFBY Crop Insurance 2026: 2% Premium',
    desc: 'Fasal kharab ho toh compensation milega. Kharif 2%, Rabi 1.5% premium. Eligibility, claim process aur enrollment deadline — PMFBY crop insurance 2026.',
    ogTitle: 'PMFBY Crop Insurance 2026 Guide',
    keywords: [
      'pmfby crop insurance 2026',
      'pmfby last date 2026',
      'pmfby last date extended 2026',
      'crop insurance last date 2026',
      'fasal bima yojana',
      'crop insurance claim',
      'pmfby enrollment',
      'प्रधानमंत्री फसल बीमा योजना',
    ],
    component: 'PmfbyCropInsurance2026',
    category: 'farming',
    publishedTime: '2026-06-20T06:39:52+05:30',
    modifiedTime: '2026-08-14T21:10:00+05:30',
    readingTime: 10,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmfbyCropInsurance2026'),
    schemes: ['pmfby'],
    ogImage: '/images/articles/pmfby-crop-insurance-2026/hero-image.webp',
    relatedSlugs: ['PmKisanMaandhanYojanaPension', 'PmKusumYojanaSolarSubsidy2026', 'bakri-palan-yojana-nlm-subsidy', 'KisanCreditCardOnlineApply2026', 'soil-health-card-complete-guide-2026'],
  },
  {
    slug: 'KisanCreditCardOnlineApply2026',
    title: 'Kisan Credit Card 2026: ₹5 Lakh Loan',
    desc: 'KCC hai to ₹5 lakh tak ka loan sirf 4% interest par mil sakta hai. Online apply process, eligibility aur zaroori documents ki puri jankari yahan.',
    ogTitle: 'KCC Online Apply — ₹5 Lakh Loan 2026',
    seoTitle: 'Kisan Credit Card 2026: 4% Byaj Online Apply',
    keywords: [
      'kisan credit card online apply 2026',
      'KCC apply online',
      'kcc loan kaise le 2026',
      'kisan credit card interest rate 2026',
      'kcc pashupalan loan',
      'kcc without cibil',
      'kcc apply sbi online',
      'किसान क्रेडिट कार्ड ऑनलाइन अप्लाई 2026',
      'किसान क्रेडिट कार्ड ब्याज दर',
    ],
    component: 'KisanCreditCardOnlineApply2026',
    category: 'loan',
    publishedTime: '2026-06-21T07:43:48+05:30',
    modifiedTime: '2026-08-18T19:45:00+05:30',
    readingTime: 14,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('KisanCreditCardOnlineApply2026'),
    banks: ['sbi', 'pnb', 'bob', 'cooperative'],
    schemes: ['kcc'],
    ogImage: '/images/kisan-credit-card-apply-online-hero.webp',
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanTractorLoan2026', 'PmKisanBankAccountChangeProcess', 'PmKusumYojanaSolarSubsidy2026', 'PmKisanMaandhanYojanaPension'],
  },
  {
    slug: 'fto-status-check-paisa-kab-aayega',
    title: 'FTO Status Check: Paisa Kab Aayega?',
    seoTitle: 'FTO Status Check 2026 — पैसा कब आता है',
    desc: 'FTO generate hone ke baad paisa kuch dino mein aata hai — official timeline nahi hai. 15-din rule, will be vs is generated ka fark aur delay ki checklist.',
    ogTitle: 'FTO Status Check — Paisa Kab Aayega 2026',
    keywords: [
      'fto status check',
      'fto will be generated',
      'fto is generated',
      'fto generated ke baad paisa kab aayega',
      'fto status check 2026',
      'pm kisan fto status',
    ],
    component: 'FtoStatusCheckPaisaKabAayega',
    category: 'status-check',
    publishedTime: '2026-08-18T07:07:40+05:30',
    modifiedTime: '2026-08-20T22:00:00+05:30',
    readingTime: 7,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('FtoStatusCheckPaisaKabAayega'),
    schemes: ['pm-kisan'],
    ogImage: '/images/pm-kisan-fto-generated-featured-image-kisanstatus.webp',
    relatedSlugs: ['pm-kisan-fto-generated-ka-matlab-kya-hai', 'PmKisanPaymentFailedFix2026', 'PmKisanBeneficiaryList2026', 'PmKisan25viKist2027', 'PmKisanMasterGuide2026'],
  },
  {
    slug: 'pm-kisan-fto-generated-ka-matlab-kya-hai',
    title: 'FTO Ka Full Form & FTO Generated Meaning',
    desc: 'FTO ka full form hai Fund Transfer Order. FTO Generated, Processed aur "will be generated" ka aasan matlab — aur paisa na aaye to 15/30 din ka action plan.',
    ogTitle: 'FTO Ka Full Form — FTO Generated/Processed Meaning',
    seoTitle: 'FTO Ka Full Form — FTO Generated Matlab',
    keywords: [
      'FTO ka full form',
      'FTO full form in hindi',
      'FTO generated meaning',
      'FTO processed meaning',
      'MB FTO transaction meaning',
      'reason for failed transaction FTO',
      'fund transfer order status',
      'pm kisan fto generated hone ke baad kitne din me paisa aata hai',
      'fto is generated and payment confirmation is pending',
      'एफटीओ जेनरेटेड क्या होता है',
      'एफटीओ का फुल फॉर्म',
    ],
    component: 'pm-kisan-fto-generated-ka-matlab-kya-hai',
    category: 'status-check',
    publishedTime: '2026-06-23T02:40:59+05:30',
    modifiedTime: '2026-08-18T07:58:15+05:30',
    readingTime: 6,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('pm-kisan-fto-generated-ka-matlab-kya-hai'),
    schemes: ['pm-kisan'],
    ogImage: '/images/pm-kisan-fto-generated-featured-image-kisanstatus.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanBeneficiaryList2026', 'PmKisanPaymentFailedFix2026', 'PmKisanBankAccountChangeProcess', 'PmKisanMasterGuide2026'],
  },
  {
    slug: 'NanoDap500mlPriceInIndia2026',
    title: 'Nano DAP 500ml Price 2026: IFFCO Rate',
    seoTitle: 'Nano DAP 500ml Price 2026 — ₹600 IFFCO Rate',
    desc: 'Nano DAP 500ml price ₹600 hai — IFFCO ka official MRP, poore desh me ek. Dealer price ₹547.50, per acre dose (500ml) aur overcharging se bachne ka tarika yahan dekhein.',
    ogTitle: 'Nano DAP 500ml Price 2026 India',
    keywords: [
      'Nano DAP 500ml price India 2026',
      'nano dap price 500 ml',
      'nano dap 500ml price',
      'nano dap 500 ml rate',
      'IFFCO Nano DAP price',
      'नैनो डीएपी 500ml कीमत 2026',
      'iffco dap price',
      'dap khad price',
    ],
    component: 'NanoDap500mlPriceInIndia2026',
    category: 'farming',
    publishedTime: '2026-06-24T04:22:58+05:30',
    modifiedTime: '2026-08-20T11:30:00+05:30',
    readingTime: 7,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('NanoDap500mlPriceInIndia2026'),
    schemes: ['nano-dap'],
    ogImage: '/images/nano-dap-500ml-bottle-hero.webp',
    relatedSlugs: ['soil-health-card-complete-guide-2026', 'AgriStackKyaHai2026', 'vermi-compost-business-guide', 'drip-sprinkler-irrigation-subsidy', 'PmKusumYojanaSolarSubsidy2026'],
  },
  {
    slug: 'PmKisan24viKist2026',
    title: 'PM Kisan 24vi Kist 2026: Date & Status',
    desc: '23vi kist 20 June ko aa chuki hai, ab 24vi ka intezaar. Pattern ke hisaab se October 2026 expected — date ka sach, status check aur taiyari ki puri jankari.',
    ogTitle: 'PM Kisan 24vi Kist — Kab Aayegi?',
    seoTitle: 'PM Kisan 24vi Kist Kab Aayegi — Date Ka Sach',
    keywords: [
      'pm kisan 24vi kist 2026',
      'pm kisan 24vi kist kab aayegi',
      'pm kisan 24th installment date 2026',
      'pm kisan next installment 2026',
      'pm kisan status check aadhar card se',
      '24vi kist beneficiary list',
      'pm kisan 2000 kab aayega',
      '24vi kist ekyc pending',
      'पीएम किसान 24वीं किस्त 2026',
      'पीएम किसान की अगली किस्त कब आएगी',
    ],
    component: 'PmKisan24viKist2026',
    category: 'status-check',
    publishedTime: '2026-06-24T02:22:07+05:30',
    modifiedTime: '2026-08-17T09:33:43+05:30',
    readingTime: 12,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisan24viKist2026'),
    schemes: ['pm-kisan'],
    ogImage: '/images/pm-kisan-24vi-kist-og.webp',
    relatedSlugs: ['PmKisan25viKist2027', 'PmKisanBeneficiaryList2026', 'pm-kisan-fto-generated-ka-matlab-kya-hai', 'PmKisanPaymentFailedFix2026', 'PmKisanMasterGuide2026'],
  },
  {
    slug: 'AgriStackKyaHai2026',
    title: 'AgriStack 2026: Digital Kisan ID Guide',
    seoTitle: 'AgriStack Kya Hai? Kisan ID Banwane Ka Tarika',
    desc: 'AgriStack wali kisan ID do tareeke se banti hai — CSC/camp se ya khud ghar baithe. Dono ka step, documents ki list, aur ID banne ke baad kya badalta hai.',
    ogTitle: 'AgriStack Kya Hai — Kisan ID Guide',
    keywords: [
      'AgriStack kya hai',
      'AgriStack 2026',
      'digital kisan ID AgriStack',
      'एग्रीस्टैक क्या है',
    ],
    component: 'AgriStackKyaHai2026',
    category: 'farming',
    publishedTime: '2026-06-24T02:22:07+05:30',
    modifiedTime: '2026-08-20T13:30:00+05:30',
    readingTime: 10,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('AgriStackKyaHai2026'),
    schemes: ['agristack', 'pm-kisan'],
    ogImage: '/images/articles/agristack-kya-hai/infographic.webp',
    relatedSlugs: ['NanoDap500mlPriceInIndia2026', 'soil-health-card-complete-guide-2026', 'PmKisanMasterGuide2026', 'PmKisanBeneficiaryList2026', 'PmKisanEkycOnline2026'],
  },
  {
    slug: 'PmKisanMasterGuide2026',
    title: 'PM Kisan Complete Guide 2026: All Fixes',
    seoTitle: 'PM Kisan Complete Guide 2026 — Har Solution',
    desc: 'PM Kisan ka har problem ek jagah — status verify, eKYC process, payment fail fix aur beneficiary list check karne ka complete step-by-step guide.',
    ogTitle: 'PM Kisan Complete Guide — Sab Fix',
    keywords: [
      'pm kisan complete guide 2026',
      'all problems solution',
      'पीएम किसान पूर्ण गाइड',
    ],
    component: 'PmKisanMasterGuide2026',
    category: 'status-check',
    publishedTime: '2026-07-05T02:01:06+05:30',
    modifiedTime: '2026-08-18T19:00:00+05:30',
    readingTime: 15,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanMasterGuide2026'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-complete-guide/hero.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanBeneficiaryList2026', 'PmKisanEkycOnline2026', 'PmKisanPaymentFailedFix2026', 'PmKisanCorrectionForm2026'],
  },
  {
    slug: 'soil-health-card-complete-guide-2026',
    title: 'Soil Health Card 2026: Mitti Test Guide',
    seoTitle: 'Soil Health Card 2026 — Mitti Test Free Apply',
    desc: 'Mitti test karwao aur sahi khaad chuno — CSC se form lo, sample do aur 15 din mein report pao. Soil Health Card banwane ka complete guide yahan.',
    ogTitle: 'Soil Health Card 2026 — Puri Jankari',
    keywords: [
      'soil health card complete guide 2026',
      'soil health card download',
      'मिट्टी स्वास्थ्य कार्ड 2026',
    ],
    component: 'soil-health-card-complete-guide-2026',
    category: 'farming',
    publishedTime: '2026-06-27T01:43:26+05:30',
    modifiedTime: '2026-08-18T19:15:00+05:30',
    readingTime: 8,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('soil-health-card-complete-guide-2026'),
    schemes: ['soil-health-card'],
    ogImage: '/images/articles/soil-health-card-complete-guide-2026/hero.webp',
    relatedSlugs: ['NanoDap500mlPriceInIndia2026', 'AgriStackKyaHai2026', 'vermi-compost-business-guide', 'drip-sprinkler-irrigation-subsidy', 'PmKusumYojanaSolarSubsidy2026'],
  },
  {
    slug: 'mandi-bhav-today',
    title: 'Aaj Ka Mandi Bhav: Daily Sabzi Rates',
    seoTitle: 'UP Mandi Bhav Aaj Ka Rate — Sabzi Phal Mausam',
    desc: 'Aaj ka mandi bhav — sabzi aur phal ke daily rates apne state ke hisaab se dekhein, saath mein 7 din ka mausam. Base data sarkari agmarknet feed se.',
    ogTitle: 'Aaj Ka Mandi Bhav — Live Rates',
    keywords: [
      'aaj ka mandi bhav',
      'mandi bhav today hindi',
      'aaj ke sabzi bhav',
    ],
    component: 'mandi-bhav-today',
    category: 'mandi',
    publishedTime: '2026-06-30T04:10:46+05:30',
    modifiedTime: '2026-08-18T19:30:00+05:30',
    readingTime: 5,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('mandi-bhav-today'),
    ogImage: '/images/articles/mandi-bhav-today/mandi-fresh-vegetables-mixed.webp',
    relatedSlugs: ['PmKisanMasterGuide2026', 'PmKisan24viKist2026', 'PmKisanBeneficiaryList2026', 'KisanRinKahaSeLe2026', 'PmKisanMaandhanYojanaPension'],
  },
  {
    slug: 'PmKisanPaymentFailedFix2026',
    title: 'PM Kisan Payment Failed 2026: 7 Fixes',
    desc: 'Payment failed dikh raha hai? Aadhaar seeding, IFSC, dormant account — 7 wajah aur turant fix ka tarika. Arrears bhi milenge.',
    ogTitle: 'PM Kisan Payment Failed Fix 2026',
    keywords: [
      'pm kisan payment failed',
      'payment fail fix',
      'aadhaar seeding dbt',
      'pm kisan paisa nahi aaya',
      'payment rejected fix',
      'पीएम किसान पेमेंट फेल',
    ],
    component: 'PmKisanPaymentFailedFix2026',
    category: 'status-check',
    publishedTime: '2026-07-06T00:28:21+05:30',
    modifiedTime: '2026-08-18T11:23:19+05:30',
    readingTime: 9,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanPaymentFailedFix2026'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-payment-failed-fix-2026/payment-failed-hero.webp',
    relatedSlugs: ['pm-kisan-fto-generated-ka-matlab-kya-hai', 'PmKisanMasterGuide2026', 'PmKisan24viKist2026', 'PmKisanBankAccountChangeProcess', 'PmKisanCorrectionForm2026'],
  },
  {
    slug: 'PmKisan26viKist',
    title: '26vi Kist Kab Aayegi: Date & List',
    seoTitle: '26vi Kist Kab Aayegi 2026 — Date, Beneficiary List, Status',
    desc: '26vi kist ki official date abhi nahi aayi — pehle 24vi aur 25vi ka cycle poora hoga. ₹2,000 hi milega. eKYC, NPCI seeding aur list mein naam check karo.',
    ogTitle: '26vi Kist Kab Aayegi — Date, List, Status',
    keywords: [
      '26vi kist kab aayegi',
      'pm kisan 26 kist kab aayegi',
      '26vi kist date',
      '26vi kist beneficiary list',
      'pm kisan 26vi kist status',
      'पीएम किसान 26वीं किस्त',
    ],
    component: 'PmKisan26viKist',
    category: 'status-check',
    publishedTime: '2026-08-18T07:43:40+05:30',
    modifiedTime: '2026-08-18T07:43:40+05:30',
    readingTime: 8,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisan26viKist'),
    schemes: ['pm-kisan'],
    // 26vi kist ~Jun 2027 hai — abhi is topic ki search demand zero hai aur page
    // site ke 2,000-word standard se neeche hai. Content live rehta hai (25vi page
    // se merged summary bhi hai), par Google se bahar — 25vi release ke baad
    // ye flag hata dena.
    noindex: true,
    ogImage: '/images/articles/pm-kisan-25vi-kist-2027/hero-25vi-kist.webp',
    relatedSlugs: ['PmKisan25viKist2027', 'PmKisan24viKist2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanBeneficiaryList2026'],
  },
  {
    slug: 'PmKisan25viKist2027',
    title: 'PM Kisan 25vi Kist 2027: Date & Amount',
    desc: '25vi kist ki koi official date nahi hai abhi — 24vi ke baad 3-4 mahine ka gap normal hai. ₹2,000 hi milega. Abhi se eKYC, bank seeding, land records theek karo.',
    ogTitle: 'PM Kisan 25vi Kist 2027 Guide',
    keywords: [
      'pm kisan 25vi kist 2027',
      '25vi kist kab aayegi',
      'pm kisan next installment',
      '25vi kist amount',
      'pm kisan feb 2027',
      'पीएम किसान 25वीं किस्त 2027',
    ],
    component: 'PmKisan25viKist2027',
    category: 'status-check',
    publishedTime: '2026-07-06T00:30:35+05:30',
    modifiedTime: '2026-08-18T18:30:00+05:30',
    readingTime: 8,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisan25viKist2027'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-25vi-kist-2027/hero-25vi-kist.webp',
    relatedSlugs: ['PmKisan24viKist2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanBeneficiaryList2026', 'PmKisanPaymentFailedFix2026'],
  },
  {
    slug: 'pm-kisan-self-registered-status-check',
    title: 'PM Kisan Self Reg Status 2026: Check',
    desc: 'Self-registration karke bhool gaye? 7-10 din baad status check karna zaroori hai. Step-by-step guide + common problems + fix.',
    ogTitle: 'PM Kisan Self Registration Status Check 2026',
    seoTitle: 'PM Kisan Self Registration Status 2026',
    keywords: [
      'pm kisan self registration status check',
      'pmkisan self registration status',
      'pm kisan self registered status',
      'pm kisan registration approval check',
      'self registration pending',
      'pm kisan status ghar baithe',
      'पीएम किसान सेल्फ रजिस्ट्रेशन स्टेटस',
    ],
    component: 'PmKisanSelfRegisteredStatusCheck',
    category: 'status-check',
    publishedTime: '2026-07-07T05:39:03+05:30',
    modifiedTime: '2026-08-20T12:15:00+05:30',
    readingTime: 10,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('pm-kisan-self-registered-status-check'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-self-registered-status-check/hero.webp',
    relatedSlugs: ['PmKisanBeneficiaryList2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanRejectedStatusReApplyGuide', 'PmKisanVoluntarySurrenderGuide'],
  },
  {
    slug: 'PmKisanCorrectionForm2026',
    title: 'PM Kisan Correction Form 2026: Fix Guide',
    desc: 'Naam spelling, IFSC ya Aadhaar seeding error? PM Kisan correction form bharne ka step-by-step tarika — portal aur CSC dono se.',
    ogTitle: 'PM Kisan Correction Form 2026 Guide',
    keywords: [
      'pm kisan correction form 2026',
      'pm kisan naam correction online',
      'pm kisan aadhaar seeding error fix',
      'pm kisan correction status check',
      'pm kisan CSC se correction',
      'pm kisan name spelling mistake fix',
    ],
    component: 'PmKisanCorrectionForm2026',
    category: 'status-check',
    publishedTime: '2026-07-08T01:55:25+05:30',
    modifiedTime: '2026-08-20T13:00:00+05:30',
    readingTime: 8,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanCorrectionForm2026'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-correction-form-2026/pm-kisan-correction-hero.webp',
    relatedSlugs: ['PmKisanPaymentFailedFix2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisan24viKist2026', 'PmKisanBankAccountChangeProcess'],
  },
  {
    slug: 'PmKusumYojanaSolarSubsidy2026',
    title: 'PM Kusum Solar Pump 2026: 60% Subsidy',
    desc: 'Solar pump par 60% subsidy, zero bijli bill, 25 saal free paani. Eligibility, online apply aur state-wise process simple bhasha mein.',
    ogTitle: 'PM Kusum Solar Subsidy 2026 Guide',
    keywords: [
      'pm kusum yojana solar pump subsidy',
      'pm kusum yojana online apply 2026',
      'pm kusum yojana registration form',
      'solar pump subsidy apply kisan',
      'pm kusum yojana status check',
      'pm kusum yojana eligibility',
    ],
    component: 'PmKusumYojanaSolarSubsidy2026',
    category: 'farming',
    publishedTime: '2026-07-08T03:06:14+05:30',
    modifiedTime: '2026-08-20T23:30:00+05:30',
    readingTime: 12,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKusumYojanaSolarSubsidy2026'),
    schemes: ['pm-kusum'],
    ogImage: '/images/articles/pm-kusum-yojana-solar-subsidy-2026/solar-pump-hero.webp',
    relatedSlugs: ['drip-sprinkler-irrigation-subsidy', 'KisanCreditCardOnlineApply2026', 'KisanTractorLoan2026', 'PmKisanMasterGuide2026', 'soil-health-card-complete-guide-2026'],
  },
  {
    slug: 'PmKisanLandSeedingForm',
    title: 'PM Kisan Land Seeding Form 2026: Poora Sach',
    desc: 'Land seeding form kahan se milta hai, kaise bharein, kaunse documents chahiye — state wise Bhulekh portal links aur khasra-khatauni ke saath poori guide.',
    ogTitle: 'PM Kisan Land Seeding Form 2026: Kahan Se Milega, Kaise Bharein',
    seoTitle: 'PM Kisan Land Seeding Form: PDF Download Ka Poora Sach',
    keywords: [
      'pm kisan land seeding form',
      'pm kisan land seeding form pdf download',
      'pm kisan land seeding form rajasthan pdf',
      'land record seeding status',
      'land seeding form state wise',
      'pm kisan khasra khatauni form',
      'pm kisan land seeding form kaise bhare',
      'land seeding no kaise fix kare',
      'pm kisan khasra number kaise dale',
    ],
    component: 'PmKisanLandSeedingForm',
    category: 'status-check',
    publishedTime: '2026-07-09T05:39:09+05:30',
    modifiedTime: '2026-08-17T11:44:57+05:30',
    readingTime: 14,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanLandSeedingForm'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-land-seeding-form/land-seeding-form-hero.webp',
    relatedSlugs: ['PmKisanBeneficiaryList2026', 'PmKisanEkycOnline2026', 'PmKisanMasterGuide2026', 'PmKisanCorrectionForm2026', 'PmKisanVillageWiseListPdfDownload'],
  },
  {
    slug: 'PmKisanFaceAuthenticationEkyc',
    title: 'PM Kisan Face Auth eKYC: Bina OTP',
    seoTitle: 'PM Kisan Face Authentication eKYC — Bina OTP',
    desc: 'OTP nahi aa raha? PM Kisan app se face authentication karke bina OTP ke eKYC complete karo. Step-by-step guide + common errors fix.',
    ogTitle: 'PM Kisan Face Auth eKYC Guide',
    keywords: [
      'pm kisan face authentication kyc',
      'pm kisan app bina otp kyc',
      'pmkisan goi app download',
      'face recognition pm kisan',
      'pm kisan mobile app ekyc',
      'bina otp pm kisan verification',
    ],
    component: 'PmKisanFaceAuthenticationEkyc',
    category: 'status-check',
    publishedTime: '2026-07-09T05:57:50+05:30',
    modifiedTime: '2026-08-20T12:30:00+05:30',
    readingTime: 10,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanFaceAuthenticationEkyc'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-face-authentication-ekyc/face-auth-hero.webp',
    relatedSlugs: ['PmKisanEkycOnline2026', 'PmKisanMasterGuide2026', 'PmKisanPaymentFailedFix2026', 'PmKisanCscRegistrationCharges', 'PmKisanMobileNumberChangeUpdate'],
  },
  {
    slug: 'PmKisanVoluntarySurrenderGuide',
    title: 'PM Kisan Surrender Guide: Kaise Hatte?',
    seoTitle: 'PM Kisan Voluntary Surrender — Kaise Hatte?',
    desc: 'Government employee ya income tax filer ho? Galti se PM Kisan mein register ho gaye toh voluntary surrender kaise karein. Online + offline process.',
    ogTitle: 'PM Kisan Voluntary Surrender Guide',
    keywords: [
      'pm kisan voluntary surrender',
      'pm kisan benefit surrender form',
      'pm kisan se kaise haten',
      'income tax filer pm kisan surrender',
      'pm kisan government employee surrender',
      'pm kisan cancel registration',
    ],
    component: 'PmKisanVoluntarySurrenderGuide',
    category: 'status-check',
    publishedTime: '2026-07-09T06:01:36+05:30',
    modifiedTime: '2026-08-18T19:30:00+05:30',
    readingTime: 12,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanVoluntarySurrenderGuide'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-voluntary-surrender/surrender-hero.webp',
    relatedSlugs: ['PmKisanMasterGuide2026', 'PmKisanCorrectionForm2026', 'PmKisanBeneficiaryList2026', 'pm-kisan-self-registered-status-check', 'PmKisanRejectedStatusReApplyGuide'],
  },
  {
    slug: 'PmKisanStateNodalOfficerList',
    title: 'PM Kisan Nodal Officer List: Contacts',
    desc: '155261 se kaam nahi ban raha? Har state ke nodal officer ka email, phone number aur address. Email template + grievance portal guide.',
    ogTitle: 'PM Kisan Nodal Officer Contact List',
    keywords: [
      'pm kisan state nodal officer list',
      'pm kisan district officer contact',
      'pm kisan complaint officer',
      'pm kisan grievance officer number',
      'pm kisan helpline state wise',
      'pm kisan district agriculture officer',
    ],
    component: 'PmKisanStateNodalOfficerList',
    category: 'status-check',
    publishedTime: '2026-07-09T06:05:43+05:30',
    modifiedTime: '2026-08-20T11:45:00+05:30',
    readingTime: 18,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanStateNodalOfficerList'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-state-nodal-officer-list/officer-hero.webp',
    relatedSlugs: ['PmKisanPaymentFailedFix2026', 'PmKisanMasterGuide2026', 'PmKisanBeneficiaryList2026', 'PmKisanCorrectionForm2026', 'PmKisanCscRegistrationCharges'],
  },
  {
    slug: 'PmKisanBankAccountChangeProcess',
    title: 'PM Kisan Bank Change 2026: Naya Account',
    desc: 'Purana account band ho gaya? CSC ya BAO office jakar naya bank account kaise link karein. NPCI seeding + IFSC update ka pura tarika.',
    ogTitle: 'PM Kisan Bank Account Change Guide',
    keywords: [
      'pm kisan bank account change kaise kare',
      'pm kisan new bank account link',
      'pm kisan bank details update',
      'pm kisan bank change csc',
      'pm kisan bank account update online',
      'pm kisan bank change form',
    ],
    component: 'PmKisanBankAccountChangeProcess',
    category: 'status-check',
    publishedTime: '2026-07-09T07:30:00+05:30',
    modifiedTime: '2026-08-20T20:15:00+05:30',
    readingTime: 16,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanBankAccountChangeProcess'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-bank-account-change/bank-change-hero.webp',
    relatedSlugs: ['PmKisanPaymentFailedFix2026', 'pm-kisan-fto-generated-ka-matlab-kya-hai', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanCscRegistrationCharges'],
  },
  {
    slug: 'PmKisanCscRegistrationCharges',
    title: 'PM Kisan CSC Charges 2026: Sahi Fees',
    desc: 'CSC wala ₹500 maang raha hai? Sarkari rate sirf ₹25-30 hai. Sahi fees, free online method, aur fraud se bachne ka tarika.',
    ogTitle: 'PM Kisan CSC Charges — Sahi Fees, Sahi Tarika',
    seoTitle: 'PM Kisan CSC Registration Charges — Sahi Fees',
    keywords: [
      'pm kisan csc registration fees',
      'pm kisan csc se kaise kare',
      'csc pm kisan charges',
      'pm kisan csc center cost',
      'pm kisan csc kitne paise leta hai',
      'pm kisan csc registration process',
    ],
    component: 'PmKisanCscRegistrationCharges',
    category: 'status-check',
    publishedTime: '2026-07-09T06:41:01+05:30',
    modifiedTime: '2026-08-18T05:24:41+05:30',
    readingTime: 14,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanCscRegistrationCharges'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-csc-registration-charges/csc-registration-hero.webp',
    relatedSlugs: ['PmKisanEkycOnline2026', 'PmKisanMasterGuide2026', 'PmKisanBankAccountChangeProcess', 'PmKisanStateNodalOfficerList', 'PmKisanMobileNumberChangeUpdate'],
  },
  {
    slug: 'PmKisanMaandhanYojanaPension',
    title: 'PM Kisan Maandhan 2026: ₹3000 Pension',
    seoTitle: 'PM Kisan Maandhan Yojana — ₹3000 Pension',
    desc: 'Chhote kisanon ke liye pension scheme. 18-40 saal ki umar mein join karo, 60 ke baad ₹3000 har mahine pao. Contribution table + apply process.',
    ogTitle: 'PM Kisan Maandhan Yojana Guide',
    keywords: [
      'pm kisan maandhan yojana',
      'kisan pension',
      'mandhan chart',
      'kisan pension yojana eligibility',
      'pm kmy pension apply',
      'pm kisan pension 3000',
      'pm kisan maan dhan yojana form',
      'pm kisan pension yojana apply online',
    ],
    component: 'PmKisanMaandhanYojanaPension',
    category: 'farming',
    publishedTime: '2026-07-09T06:45:51+05:30',
    modifiedTime: '2026-08-20T20:15:00+05:30',
    readingTime: 16,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanMaandhanYojanaPension'),
    schemes: ['pm-kisan', 'pm-kmy'],
    ogImage: '/images/articles/pm-kisan-maandhan-yojana-pension/maandhan-hero.webp',
    relatedSlugs: ['PmKisanMasterGuide2026', 'PmKisanBeneficiaryList2026', 'PmKisanEkycOnline2026', 'PmfbyCropInsurance2026', 'bakri-palan-yojana-nlm-subsidy'],
  },
  {
    slug: 'PmKisanRejectedStatusReApplyGuide',
    title: 'PM Kisan Rejected Status 2026: Reapply',
    seoTitle: 'PM Kisan Rejected Status — Dobara Apply Kaise',
    desc: 'Status rejected dikh raha hai? 7 main reasons + step-by-step re-application guide. CSC correction form + arrears claim process.',
    ogTitle: 'PM Kisan Rejected Status Fix Guide',
    keywords: [
      'pm kisan rejected status fix',
      'pm kisan reapply kaise kare',
      'pm kisan rejection reason',
      'pm kisan rejected list solution',
      'pm kisan application rejected kya kare',
      'pm kisan rejected name list',
    ],
    component: 'PmKisanRejectedStatusReApplyGuide',
    category: 'status-check',
    publishedTime: '2026-07-09T06:50:50+05:30',
    modifiedTime: '2026-08-20T13:45:00+05:30',
    readingTime: 17,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanRejectedStatusReApplyGuide'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-rejected-status-re-apply-guide/rejected-status-hero.webp',
    relatedSlugs: ['PmKisanBeneficiaryList2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026', 'PmKisanCorrectionForm2026', 'pm-kisan-self-registered-status-check'],
  },
  {
    slug: 'PmKisanVillageWiseListPdfDownload',
    title: 'PM Kisan Village List 2026: PDF Download',
    desc: 'Apne gaon ki puri PM Kisan beneficiary list PDF mein download karo. Mobile + PC dono tarika. Excel convert trick + state portals.',
    ogTitle: 'PM Kisan Village Wise List PDF',
    keywords: [
      'pm kisan village wise list pdf',
      'pm kisan gaon wise list download',
      'pm kisan pdf roster',
      'pm kisan village list kaise dekhe',
      'pm kisan gaon ki list',
      'pm kisan village wise beneficiary list',
    ],
    component: 'PmKisanVillageWiseListPdfDownload',
    category: 'status-check',
    publishedTime: '2026-07-09T06:54:59+05:30',
    modifiedTime: '2026-08-20T22:45:00+05:30',
    readingTime: 15,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanVillageWiseListPdfDownload'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-village-wise-list-pdf-download/village-list-hero.webp',
    relatedSlugs: ['PmKisanBeneficiaryList2026', 'PmKisanRejectedStatusReApplyGuide', 'PmKisanMasterGuide2026', 'PmKisanStateNodalOfficerList', 'PmKisanLandSeedingForm'],
  },
  {
    slug: 'PmKisanMobileNumberChangeUpdate',
    title: 'PM Kisan Mobile Change 2026: Naya SIM',
    desc: 'Purana SIM band hai aur OTP nahi aa raha? CSC ya BAO office jakar naya mobile number kaise link karein. Online vs offline complete guide.',
    ogTitle: 'PM Kisan Mobile Number Change Guide',
    keywords: [
      'pm kisan mobile number change',
      'pm kisan mobile number update',
      'pm kisan sim change kaise kare',
      'pm kisan bina purane sim mobile update',
      'pm kisan mobile number update csc',
      'pm kisan mobile number change online',
    ],
    component: 'PmKisanMobileNumberChangeUpdate',
    category: 'status-check',
    publishedTime: '2026-07-09T06:59:32+05:30',
    modifiedTime: '2026-08-17T09:37:11+05:30',
    readingTime: 15,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('PmKisanMobileNumberChangeUpdate'),
    schemes: ['pm-kisan'],
    ogImage: '/images/articles/pm-kisan-mobile-number-change-update/mobile-change-hero.webp',
    relatedSlugs: ['PmKisanCscRegistrationCharges', 'PmKisanEkycOnline2026', 'PmKisanMasterGuide2026', 'PmKisanRejectedStatusReApplyGuide', 'PmKisanFaceAuthenticationEkyc'],
  },
  {
    slug: 'bakri-palan-yojana-nlm-subsidy',
    title: 'Bakri Palan Yojana 2026: NLM Subsidy',
    seoTitle: 'NLM Bakri Palan Yojana 2026 — 50% Subsidy',
    desc: 'NLM bakri palan: 50% subsidy — kisan, SHG aur FPO sab eligible. 20 bakri farm ka budget, apply process aur 5-saal ka profit projection yahan.',
    ogTitle: 'Bakri Palan Yojana 2026 Guide',
    keywords: [
      'nlm bakri palan yojana',
      'nlm bakri palan',
      'bakri palan yojana 2026',
      'nlm bakri palan online apply',
      'nlm subsidy goat farming',
      'bakri palan subsidy kaise milegi',
      'bakri palan profit kitna hota hai',
      'goat farming loan process',
      'bakri palan nasl kaunsi chunein',
    ],
    component: 'BakriPalanYojana',
    category: 'pashupalan',
    publishedTime: '2026-07-12T05:03:13+05:30',
    modifiedTime: '2026-08-20T13:10:00+05:30',
    readingTime: 18,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('bakri-palan-yojana-nlm-subsidy'),
    schemes: ['nlm', 'pm-kisan'],
    ogImage: '/images/kisanguides/bakri-palan-nlm-subsidy.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'PmfbyCropInsurance2026', 'mushroom-kheti-nhb-subsidy'],
  },
  {
    slug: 'mushroom-kheti-nhb-subsidy',
    title: 'Mushroom Kheti 2026: NHB Subsidy Guide',
    desc: 'NHB mushroom subsidy: general category ko ~40% back-ended capital subsidy. Apply process, 100-bag unit ka budget aur ₹40,000+ mahina profit plan.',
    ogTitle: 'Mushroom Kheti 2026 — Profit Guide',
    keywords: [
      'mushroom kheti 2026',
      'oyster mushroom farming subsidy',
      'mushroom kheti kaise shuru karein',
      'mushroom farming profit kitna hota hai',
      'nhb subsidy mushroom',
      'nhb subsidy for mushroom farming',
      'national horticulture board mushroom subsidy',
      'mushroom cultivation process',
    ],
    component: 'MushroomKheti',
    category: 'agri-business',
    publishedTime: '2026-07-12T05:07:08+05:30',
    modifiedTime: '2026-08-20T13:20:00+05:30',
    readingTime: 16,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('mushroom-kheti-nhb-subsidy'),
    schemes: ['nhb', 'pm-fme'],
    ogImage: '/images/kisanguides/harvesting-mushroom.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'bakri-palan-yojana-nlm-subsidy', 'madhumakhi-palan-kvic-subsidy'],
  },
  {
    slug: 'madhumakhi-palan-kvic-subsidy',
    title: 'Madhumakhi Palan 2026: KVIC Subsidy',
    desc: 'Beekeeping se dohri kamai - shahad + pollination. 50-box unit ka budget, KVIC subsidy 80% tak, aur real profit calculation.',
    ogTitle: 'Madhumakhi Palan 2026 Guide',
    keywords: [
      'madhumakhi palan 2026',
      'beekeeping subsidy kvic',
      'madhumakhi palan kaise shuru karein',
      'madhumakhi palan profit kitna hota hai',
      'honey bee farming subsidy',
      'madhumakhi palan cost breakdown',
    ],
    component: 'MadhumakhiPalan',
    category: 'pashupalan',
    publishedTime: '2026-07-12T05:10:43+05:30',
    modifiedTime: '2026-08-20T22:30:00+05:30',
    readingTime: 17,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('madhumakhi-palan-kvic-subsidy'),
    schemes: ['kvic', 'nhb', 'pm-fme'],
    ogImage: '/images/kisanguides/madhumakhi-palan-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'mushroom-kheti-nhb-subsidy', 'pm-matsya-sampada-yojana-fish-farming'],
  },
  {
    slug: 'pm-matsya-sampada-yojana-fish-farming',
    title: 'PM Matsya Yojana 2026: 60% Subsidy',
    desc: 'Fish farming par 40-60% subsidy. 1 acre pond ka complete budget, Biofloc vs Traditional, aur 3-year profit projection.',
    ogTitle: 'PM Matsya Sampada Yojana 2026',
    keywords: [
      'pm matsya sampada yojana 2026',
      'fish farming subsidy 60 percent',
      'machli palan kaise shuru karein',
      'fish farming profit kitna hota hai',
      'biofloc technology fish farming',
      'pmmsy subsidy eligibility',
    ],
    component: 'PMatsyaSampada',
    category: 'pashupalan',
    publishedTime: '2026-07-12T05:16:10+05:30',
    modifiedTime: '2026-08-18T05:24:41+05:30',
    readingTime: 18,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('pm-matsya-sampada-yojana-fish-farming'),
    schemes: ['pmmsy', 'pm-kisan'],
    ogImage: '/images/kisanguides/fish-farming-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'madhumakhi-palan-kvic-subsidy', 'silage-making-business-guide'],
  },
  {
    slug: 'silage-making-business-guide',
    title: 'Silage Business 2026: SMAM Subsidy',
    seoTitle: 'Silage Business 2026 — Makka Se Kamai Ka Plan',
    desc: 'Silage business se mahine ka ₹50,000+ kamayein. 100-bag unit ka complete budget, SMAM subsidy, aur real profit calculation.',
    ogTitle: 'Silage Making Business 2026 Guide',
    keywords: [
      'silage making business 2026',
      'silage business profit kitna hota hai',
      'silage making kaise shuru karein',
      'silage business cost breakdown',
      'smam subsidy silage making',
      'silage business risk aur challenges',
    ],
    component: 'SilageMaking',
    category: 'pashupalan',
    publishedTime: '2026-07-12T05:24:38+05:30',
    modifiedTime: '2026-08-13T07:03:42+05:30',
    readingTime: 16,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('silage-making-business-guide'),
    schemes: ['smam', 'aif', 'pm-fme'],
    ogImage: '/images/kisanguides/silage-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'pm-matsya-sampada-yojana-fish-farming', 'custom-hiring-centre-chc-portal'],
  },
  {
    slug: 'pm-fme-yojana-food-processing',
    title: 'PM FME Yojana 2026: 35% Subsidy',
    desc: 'PM FME se 35% subsidy (max ₹10 lakh). Achar, papad, bakery units ke liye. ODOP benefits, application process, aur documents checklist.',
    ogTitle: 'PM FME Yojana 2026 Food Subsidy',
    keywords: [
      'pm fme yojana 2026',
      'pm fme subsidy 35 percent',
      'pm fme kaise apply karein',
      'pm fme eligibility criteria',
      'pm fme odop scheme',
      'pm fme food processing subsidy',
    ],
    component: 'PMFMEYojana',
    category: 'agri-business',
    publishedTime: '2026-07-12T05:28:29+05:30',
    modifiedTime: '2026-08-13T23:23:53+05:30',
    readingTime: 15,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('pm-fme-yojana-food-processing'),
    schemes: ['pm-fme', 'pmegp'],
    ogImage: '/images/kisanguides/pmfhero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'PmKisanMaandhanYojanaPension', 'vermi-compost-business-guide', 'mushroom-kheti-nhb-subsidy'],
  },
  {
    slug: 'custom-hiring-centre-chc-portal',
    title: 'Custom Hiring Centre 2026: SMAM Guide',
    desc: 'CHC khol kar machinery rent se kamayein. SMAM subsidy 40-50%, 8 implements ka complete budget, aur real profit calculation.',
    ogTitle: 'Custom Hiring Centre 2026 Guide',
    keywords: [
      'custom hiring centre 2026',
      'chc portal registration',
      'chc business profit kitna hota hai',
      'smam subsidy farm machinery',
      'chc kaise shuru karein',
      'chc business cost breakdown',
    ],
    component: 'CHCPortal',
    category: 'agri-business',
    publishedTime: '2026-07-12T05:32:56+05:30',
    modifiedTime: '2026-08-20T22:10:00+05:30',
    readingTime: 17,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('custom-hiring-centre-chc-portal'),
    schemes: ['smam', 'pm-kisan'],
    ogImage: '/images/kisanguides/chc-portal-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanTractorLoan2026', 'KisanCreditCardOnlineApply2026', 'silage-making-business-guide', 'drip-sprinkler-irrigation-subsidy'],
  },
  {
    slug: 'vermi-compost-business-guide',
    title: 'Vermi Compost Business 2026: PKVY Guide',
    desc: 'Vermi compost business se organic fertilizer bechein. PKVY subsidy 50-75%, 10-pit unit ka budget, aur real profit calculation.',
    ogTitle: 'Vermi Compost Business 2026 Guide',
    keywords: [
      'vermi compost business 2026',
      'vermi compost kaise banayein',
      'vermi compost profit kitna hota hai',
      'vermi compost subsidy pkvy',
      'vermi compost business cost breakdown',
      'vermi compost risk aur challenges',
    ],
    component: 'VerminCompost',
    category: 'agri-business',
    publishedTime: '2026-07-12T05:37:32+05:30',
    modifiedTime: '2026-08-18T05:24:41+05:30',
    readingTime: 16,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('vermi-compost-business-guide'),
    schemes: ['pkvy', 'pm-fme'],
    ogImage: '/images/kisanguides/vermi-compost-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'soil-health-card-complete-guide-2026', 'drip-sprinkler-irrigation-subsidy', 'pm-fme-yojana-food-processing'],
  },
  {
    slug: 'drip-sprinkler-irrigation-subsidy',
    title: 'Drip Sprinkler Subsidy: PDMC ke 55% / 45% Niyam',
    desc: 'PDMC micro-irrigation subsidy ka asli structure — small/marginal kisan ko 55%, baaki ko 45% assistance, unit cost norms, state top-up aur application process.',
    ogTitle: 'Drip Sprinkler Subsidy: Asli PDMC Rates',
    keywords: [
      'drip irrigation subsidy',
      'sprinkler irrigation subsidy',
      'pmksy per drop more crop',
      'pdmc subsidy 55 percent',
      'drip vs sprinkler kaunsa behtar',
      'micro irrigation unit cost norms',
      'drip irrigation kaise lagwayein',
    ],
    component: 'DripSprinkler',
    category: 'agri-business',
    publishedTime: '2026-07-12T05:41:02+05:30',
    modifiedTime: '2026-08-17T04:17:55+05:30',
    readingTime: 15,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('drip-sprinkler-irrigation-subsidy'),
    schemes: ['pmksy', 'pm-kusum'],
    ogImage: '/images/kisanguides/drip-sprinkler-hero.webp',
    relatedSlugs: ['PmKusumYojanaSolarSubsidy2026', 'KisanCreditCardOnlineApply2026', 'soil-health-card-complete-guide-2026', 'NanoDap500mlPriceInIndia2026', 'PmKisanMaandhanYojanaPension'],
  },
  {
    slug: 'namo-drone-didi-yojana-shg-selection',
    title: 'Namo Drone Didi 2026: SHG Selection Sach',
    seoTitle: 'Namo Drone Didi Yojana 2026 — SHG Se Selection',
    desc: 'Koi online form nahi hai — selection DAY-NRLM ke SHG network se hota hai. 80% madad ₹8 lakh tak, 15 din training ka structure aur kamai ka realistic ganit.',
    ogTitle: 'Namo Drone Didi 2026 — Selection Ka Asli Rasta',
    keywords: [
      'namo drone didi yojana shg selection process',
      'drone didi banne ke liye kya karna padega',
      'mahila shg drone training 15 din',
      'drone pilot certificate 10th pass mahila',
      'day nrlm drone yojana block office',
      'drone spray service rate per acre',
      'नमो ड्रोन दीदी योजना चयन प्रक्रिया',
    ],
    component: 'NamoDroneDidiYojana',
    category: 'agri-business',
    publishedTime: '2026-08-15T18:40:12+05:30',
    modifiedTime: '2026-08-16T07:05:00+05:30',
    readingTime: 15,
    author: AUTHOR_NAME,
    authorBio: getAuthorBio('namo-drone-didi-yojana-shg-selection'),
    schemes: ['namo-drone-didi', 'day-nrlm'],
    ogImage: '/images/articles/namo-drone-didi-yojana-shg-selection/drone-didi-spray-hero.webp',
    relatedSlugs: ['custom-hiring-centre-chc-portal', 'drip-sprinkler-irrigation-subsidy', 'KisanCreditCardOnlineApply2026', 'NanoDap500mlPriceInIndia2026', 'PmKusumYojanaSolarSubsidy2026'],
  },
] as const;
