import { AUTHOR_NAME } from '@/lib/site-config';
import type { HindiArticle } from '@/lib/hindi-articles-data';

// Rajya (state) yojana articles — Hindi (Devanagari) versions.
// Hinglish originals live in lib/rajya-yojana-data.ts + app/rajya-yojana/.
// URL structure unchanged: /articles/hi/<slug> (see lib/hindi-hreflang.ts for mapping).
export const HINDI_RAJYA_YOJANA_ARTICLES: readonly HindiArticle[] = [
  {
    slug: 'hi/mp-kisan-kalyan-yojana',
    titleHi: 'MP किसान कल्याण योजना — ₹12000 सालाना कैसे मिलेंगे? जानिए',
    seoTitleHi: 'MP किसान कल्याण योजना — ₹12000 कैसे मिलेंगे?',
    desc: 'MP मुख्यमंत्री किसान कल्याण योजना से हर साल ₹12000 पाएं — kisan kalyan yojana status check, पात्रता और अगली किस्त की date की पूरी जानकारी हिंदी में देखें।',
    keywords: ['मुख्यमंत्री किसान कल्याण योजना', 'mp kisan kalyan yojana status', '₹12000 किसान योजना MP'],
    category: 'farming',
    publishedTime: '2026-04-17T21:51:25+05:30',
    modifiedTime: '2026-04-22T14:56:07+05:30',
    author: AUTHOR_NAME,
    component: 'MukhyamantriKisanKalyanYojanaMp',
    ogImage: '/images/articles/hindi-yojna/mp-kisan-kalyan/mp-farmer-field.webp',
  },
  {
    slug: 'hi/namo-shetkari-yojana',
    titleHi: 'नमो शेतकरी योजना — ₹12000 की किस्त कब और कैसे मिलेगी? जानिए',
    seoTitleHi: 'नमो शेतकरी योजना — ₹12000 किस्त कब मिलेगी',
    desc: 'नमो शेतकरी महासन्मान निधि से Maharashtra के किसानों को ₹12000 सालाना — namo shetkari yojana status check, पात्रता और किस्त न आए तो solution यहां देखें।',
    keywords: ['नमो शेतकरी योजना', 'namo shetkari yojana status', 'namo shetkari mahasanman nidhi', 'नमो शेतकरी महासन्मान निधी'],
    category: 'farming',
    publishedTime: '2026-07-05T18:35:14+05:30',
    modifiedTime: '2026-07-14T12:58:52+05:30',
    author: AUTHOR_NAME,
    component: 'NamoShetkariYojanaMaharashtra',
    ogImage: '/images/articles/hindi-yojna/namo-shetkari/shetkari-field.webp',
  },
  {
    slug: 'hi/rajasthan-kisan-samman-nidhi',
    titleHi: 'राजस्थान किसान सम्मान निधि — ₹9,000 का हिसाब और किस्त की स्थिति',
    seoTitleHi: 'राजस्थान किसान सम्मान निधि — ₹9,000 और किस्त स्थिति',
    desc: 'राजस्थान के किसान को पीएम किसान के ₹6,000 के ऊपर राज्य से ₹3,000 — कुल ₹9,000। जन आधार से किस्त की स्थिति देखने का तरीका और पैसा अटकने की चार असली वजहें यहां।',
    keywords: [
      'राजस्थान किसान सम्मान निधि',
      'rajasthan kisan samman nidhi',
      'मुख्यमंत्री किसान सम्मान निधि राजस्थान',
      'mukhyamantri kisan samman nidhi rajasthan',
      'राजस्थान किसान सम्मान निधि किस्त स्थिति',
      'jan aadhaar se kisan samman nidhi status',
      'जन सूचना पोर्टल किसान सम्मान निधि',
      'rajasthan kisan samman nidhi 9000',
    ],
    category: 'farming',
    publishedTime: '2026-08-16T21:30:00+05:30',
    modifiedTime: '2026-08-16T21:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'RajasthanKisanSammanNidhiHindi',
    ogImage: '/images/articles/rajya-yojna/rajasthan-kisan-samman-nidhi-9000/hero.webp',
  },
  {
    slug: 'hi/annadata-sukhibhava-status',
    titleHi: 'अन्नदाता सुखीभव स्थिति — ₹20,000 और CCRC का पूरा हिसाब',
    seoTitleHi: 'अन्नदाता सुखीभव स्थिति — ₹20,000 और CCRC कार्ड',
    desc: 'आंध्र प्रदेश की अन्नदाता सुखीभव से ₹20,000 सालाना — आधार से स्थिति देखने का तरीका, किस्तों का दर्ज हिसाब, और बटाईदार किसान के लिए CCRC कार्ड की पूरी बात।',
    keywords: [
      'अन्नदाता सुखीभव स्थिति',
      'annadata sukhibhava status check',
      'अन्नदाता सुखीभव ₹20000',
      'annadata sukhibhava beneficiary list',
      'ccrc card kya hai',
      'बटाईदार किसान अन्नदाता सुखीभव',
      'ysr rythu bharosa naya naam',
      'annadathasukhibhava ap gov in status',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T22:15:00+05:30',
    modifiedTime: '2026-08-16T22:15:00+05:30',
    author: AUTHOR_NAME,
    component: 'AnnadataSukhibhavaStatusHindi',
    ogImage: '/images/articles/rajya-yojna/annadata-sukhibhava-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/rythu-bharosa-status',
    titleHi: 'रायथु भरोसा स्थिति — बंधु से भरोसा तक, ₹12,000 प्रति एकड़ का हिसाब',
    seoTitleHi: 'रायथु भरोसा स्थिति — ₹12,000 प्रति एकड़ का हिसाब',
    desc: 'तेलंगाना की रायथु भरोसा से ₹6,000 प्रति एकड़ हर मौसम — रायथु बंधु से असली फर्क, आधार से स्टेटस चेक और भू भारती रिकॉर्ड की रुकावटें।',
    keywords: [
      'रायथु भरोसा स्थिति',
      'rythu bharosa status check',
      'रायथु बंधु बनाम रायथु भरोसा',
      'rythu bharosa 12000 per acre',
      'rythu bharosa beneficiary list',
      'रायथु भरोसा किस्त कब आएगी',
      'rythu bharosa telangana kist',
      'भू भारती जमीन रिकॉर्ड तेलंगाना',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T23:45:00+05:30',
    modifiedTime: '2026-08-16T23:45:00+05:30',
    author: AUTHOR_NAME,
    component: 'RythuBharosaStatusHindi',
    ogImage: '/images/articles/rajya-yojna/rythu-bharosa-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/krishak-bandhu-status',
    titleHi: 'कृषक बंधु स्थिति — वोटर कार्ड से किस्त और ₹2 लाख का हिसाब',
    seoTitleHi: 'कृषक बंधु स्थिति — वोटर कार्ड से किस्त, ₹2 लाख',
    desc: 'पश्चिम बंगाल की कृषक बंधु में स्थिति वोटर कार्ड (EPIC) से खुलती है — खोजने का सही तरीका, ₹10,000 सालाना का स्लैब और ₹2 लाख डेथ बेनिफिट का दावा।',
    keywords: [
      'कृषक बंधु स्थिति',
      'krishak bandhu status check voter id',
      'कृषक बंधु वोटर कार्ड से चेक',
      'krishak bandhu 10000 per year',
      'कृषक बंधु डेथ बेनिफिट 2 लाख',
      'krishak bandhu beneficiary list',
      'krishakbandhu wb gov in status',
      'কৃষক বন্ধু status',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T00:30:00+05:30',
    modifiedTime: '2026-08-17T00:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'KrishakBandhuStatusHindi',
    ogImage: '/images/articles/rajya-yojna/krishak-bandhu-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/odisha-cm-kisan-status',
    titleHi: 'ओडिशा CM Kisan स्थिति — भूमिहीन को भी ₹12,500 का रास्ता',
    seoTitleHi: 'ओडिशा CM Kisan स्थिति — भूमिहीन को ₹12,500',
    desc: 'KALIA की जगह आई ओडिशा CM Kisan — आधार से स्टेटस चेक, जमीन वालों को ₹4,000 और भूमिहीन परिवार को ₹12,500 का हिसाब, और पैसा अटकने की आम वजहें।',
    keywords: [
      'ओडिशा सीएम किसान स्थिति',
      'odisha cm kisan status check',
      'cm kisan odisha भूमिहीन 12500',
      'cm kisan beneficiary list odisha',
      'kalia yojana नया नाम',
      'cmkisan odisha gov in status',
      'सीएम किसान योजना ओडिशा लिस्ट',
      'cm kisan village wise list',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T09:30:00+05:30',
    modifiedTime: '2026-08-17T09:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'OdishaCmKisanStatusHindi',
    ogImage: '/images/articles/rajya-yojna/odisha-cm-kisan-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/pati-patni-pm-kisan-rule',
    titleHi: 'पति-पत्नी दोनों को PM Kisan मिलेगा? नियम का सीधा जवाब',
    seoTitleHi: 'पति-पत्नी दोनों को PM Kisan मिलेगा? Family Rule',
    desc: 'नहीं — एक परिवार (पति, पत्नी, नाबालिग बच्चे) में सिर्फ एक को PM Kisan मिलता है। गाइडलाइन का नियम, असली केस और गलत पंजीकरण सरेंडर करने का तरीका।',
    keywords: [
      'पति पत्नी दोनों को पीएम किसान',
      'pm kisan pati patni dono ko milega',
      'pm kisan family rule',
      'पीएम किसान एक परिवार एक लाभ',
      'pm kisan voluntary surrender kaise kare',
      'pm kisan recovery notice paisa wapas',
      'पीएम किसान पात्रता परिवार की परिभाषा',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T11:30:00+05:30',
    modifiedTime: '2026-08-17T11:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'PatiPatniPmKisanRuleHindi',
    ogImage: '/images/articles/rajya-yojna/pm-kisan-pati-patni-dono-ko-milega/hero.webp',
  },
  {
    slug: 'hi/state-kisan-yojana-list',
    titleHi: 'राज्य किसान योजना लिस्ट 2026 — किस राज्य में कितना पैसा मिलता है?',
    seoTitleHi: 'राज्य किसान योजना लिस्ट 2026 — State Wise Amount',
    desc: 'PM Kisan के ₹6,000 के ऊपर आपका राज्य कितना देता है? MP, राजस्थान, महाराष्ट्र, AP, तेलंगाना, बंगाल, ओडिशा — हर राज्य की योजना, रकम और स्टेटस लिंक।',
    keywords: [
      'राज्य किसान योजना लिस्ट',
      'state kisan yojana list 2026',
      'किस राज्य में किसान को कितना पैसा मिलता है',
      'pm kisan ke upar state yojana',
      'मुख्यमंत्री किसान योजना सभी राज्य',
      'kisan yojana state wise amount',
      'राज्य सरकार किसान सहायता योजना',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T13:30:00+05:30',
    modifiedTime: '2026-08-17T13:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'StateKisanYojanaListHindi',
    ogImage: '/images/articles/rajya-yojna/state-kisan-yojana-list-all-states-2026/hero.webp',
  },
  {
    slug: 'hi/krishak-unnati-yojana-status',
    titleHi: 'कृषक उन्नति योजना स्टेटस 2026 — अंतर राशि कब और कितनी मिलेगी?',
    seoTitleHi: 'कृषक उन्नति योजना स्टेटस — अंतर राशि 2026',
    desc: 'छत्तीसगढ़ में धान बेचा है? ₹3,100 प्रति क्विंटल तक की अंतर राशि का हिसाब, एकमुश्त भुगतान का नया नियम, स्टेटस चेक और ₹15,000 प्रति एकड़ वाला फायदा।',
    keywords: [
      'कृषक उन्नति योजना',
      'krishak unnati yojana status check',
      'अंतर राशि कब आएगी 2026',
      'dhan antar rashi chhattisgarh',
      'धान खरीदी अंतर राशि स्टेटस',
      'krishak unnati yojana 15000 per acre',
      'छत्तीसगढ़ धान 3100 प्रति क्विंटल',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T15:30:00+05:30',
    modifiedTime: '2026-08-17T15:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'KrishakUnnatiYojanaStatusHindi',
    ogImage: '/images/articles/rajya-yojna/krishak-unnati-yojana-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/meri-fasal-mera-byora-status',
    titleHi: 'मेरी फसल मेरा ब्योरा स्टेटस 2026 — रजिस्ट्रेशन से MSP भुगतान तक',
    seoTitleHi: 'मेरी फसल मेरा ब्योरा स्टेटस चेक 2026 — Gate Pass Tak',
    desc: 'हरियाणा में fasal.haryana.gov.in पर स्टेटस चेक, पटवारी सत्यापन, गेट पास और MSP भुगतान अटकने की 4 वजहें — पांच पड़ावों में पूरा सफर, फैमिली ID की भूमिका समेत।',
    keywords: [
      'मेरी फसल मेरा ब्योरा',
      'meri fasal mera byora status check',
      'मेरी फसल मेरा ब्योरा स्टेटस',
      'fasal haryana gov in रजिस्ट्रेशन',
      'गेट पास हरियाणा मंडी',
      'फैमिली आईडी से फसल रजिस्ट्रेशन',
      'mfmb status check',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T19:30:00+05:30',
    modifiedTime: '2026-08-16T19:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'MeriFasalMeraByoraStatusHindi',
    ogImage: '/images/articles/rajya-yojna/meri-fasal-mera-byora-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/bihar-kisan-registration-status',
    titleHi: 'बिहार किसान पंजीकरण स्टेटस 2026 — 13 अंकों का नंबर, सारी योजनाओं का दरवाजा',
    seoTitleHi: 'बिहार किसान पंजीकरण स्टेटस चेक 2026 — DBT Bihar',
    desc: 'DBT Agriculture Bihar पर 13 अंकों की पंजीकरण संख्या भूल गए? आधार से निकालने का तरीका, स्टेटस चेक और डीजल, इनपुट, बीज अनुदान — हर अर्जी का हाल एक जगह।',
    keywords: [
      'बिहार किसान पंजीकरण स्टेटस',
      'dbt agriculture bihar status check',
      'किसान पंजीकरण संख्या कैसे निकालें',
      'kisan registration number bihar kaise nikale',
      'डीजल अनुदान स्टेटस बिहार',
      'कृषि इनपुट अनुदान स्टेटस चेक',
      'dbtagriculture bihar gov in registration',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T21:30:00+05:30',
    modifiedTime: '2026-08-16T21:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'BiharKisanRegistrationStatusHindi',
    ogImage: '/images/articles/rajya-yojna/bihar-kisan-registration-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/parihara-payment-status',
    titleHi: 'परिहार पेमेंट स्टेटस 2026 — फसल नुकसान मुआवजा कहां अटका, कैसे देखें?',
    seoTitleHi: 'परिहार पेमेंट स्टेटस चेक 2026 — Karnataka Parihara',
    desc: 'कर्नाटक में फसल नुकसान (bele hani) का मुआवजा — parihara.karnataka.gov.in पर आधार या गांव की सूची से स्टेटस, SDRF दरें, FRUITS ID और अटके पैसे का हर रास्ता।',
    keywords: [
      'परिहार पेमेंट स्टेटस',
      'parihara payment status check',
      'फसल नुकसान मुआवजा कर्नाटक',
      'parihara karnataka gov in status',
      'बेले हानी मुआवजा स्टेटस',
      'FRUITS ID karnataka kisan',
      'फसल मुआवजा village wise list',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T22:30:00+05:30',
    modifiedTime: '2026-08-16T22:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'PariharaPaymentStatusHindi',
    ogImage: '/images/articles/rajya-yojna/parihara-payment-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/up-kisan-karj-rahat-list',
    titleHi: 'UP किसान कर्ज राहत लिस्ट 2026 — नई माफी का सच और नाम देखने का तरीका',
    seoTitleHi: 'UP किसान कर्ज राहत लिस्ट 2026 — Rin Mochan Status',
    desc: 'क्या 2026 में नई कर्ज माफी आई है? ईमानदार जवाब, साथ में upkisankarjrahat.upsdc.gov.in पर लिस्ट में नाम देखने, शिकायत और fake लिंक से बचने का पूरा रास्ता।',
    keywords: [
      'UP किसान कर्ज राहत लिस्ट',
      'up kisan karj rahat list 2026',
      'किसान रिण मोचन योजना स्टेटस',
      'कर्ज माफी लिस्ट में नाम कैसे देखें',
      'upkisankarjrahat upsdc gov in',
      'यूपी कर्ज माफी नई लिस्ट',
      'kisan karj mafi up shikayat status',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T23:30:00+05:30',
    modifiedTime: '2026-08-16T23:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'UpKisanKarjRahatListHindi',
    ogImage: '/images/articles/rajya-yojna/up-kisan-karj-rahat-list-2026/hero.webp',
  },
  {
    slug: 'hi/ikhedut-portal-status',
    titleHi: 'iKhedut पोर्टल स्टेटस चेक 2026 — अर्जी नंबर से सब्सिडी तक',
    seoTitleHi: 'iKhedut पोर्टल अर्जी स्टेटस चेक 2026 — पूरा तरीका',
    desc: 'iKhedut पोर्टल पर अर्जी का स्टेटस 2 मिनट में देखें — अर्जी नंबर खो गया तो कैसे निकालें, pending से payment तक हर स्थिति का मतलब और ट्रैक्टर सहाय का पूरा सफर।',
    keywords: [
      'ikhedut portal status',
      'iKhedut अर्जी स्टेटस चेक',
      'ikhedut arji status check',
      'ikhedut gujarat gov in स्टेटस',
      'ट्रैक्टर सहाय योजना गुजरात स्टेटस',
      'ikhedut arji number kaise nikale',
      'iKhedut योजना लिस्ट 2026',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T01:20:00+05:30',
    modifiedTime: '2026-08-17T01:20:00+05:30',
    author: AUTHOR_NAME,
    component: 'IkhedutPortalStatusHindi',
    ogImage: '/images/articles/rajya-yojna/ikhedut-portal-status-check-2026/hero.webp',
  },
] as const;
