import { AUTHOR_NAME } from '@/lib/site-config';
import type { HindiArticle } from '@/lib/hindi-articles-data';

// Hindi (Devanagari) versions of the new 2026 yojana articles
// (SEO-KEYWORDS-RANK1-PLAN.md). Components live in
// components/articles/hindi-yojana-2026/. URLs: /articles/hi/<slug>.
export const HINDI_YOJANA_2026_ARTICLES: readonly HindiArticle[] = [
  {
    slug: 'hi/fasal-bima-claim-status',
    titleHi: 'फसल बीमा क्लेम स्टेटस — पैसा कब और कैसे मिलेगा',
    seoTitleHi: 'फसल बीमा क्लेम स्टेटस — पैसा कब मिलेगा',
    desc: 'PMFBY क्लेम अटका है? pmfby.gov.in पर status check का तरीका, 72 घंटे का नियम, claim reject होने के असली कारण और 14447 से शिकायत तक — पूरा रास्ता यहां।',
    keywords: [
      'फसल बीमा क्लेम स्टेटस',
      'fasal bima claim status',
      'फसल बीमा का पैसा कब आएगा',
      'pmfby claim status check',
      'फसल बीमा क्लेम रिजेक्ट',
      'फसल बीमा शिकायत नंबर 14447',
      'pmfby 72 hours rule hindi',
      'फसल बीमा क्लेम कितने दिन में आता है',
    ],
    category: 'farming',
    publishedTime: '2026-08-18T07:49:14+05:30',
    modifiedTime: '2026-08-18T07:49:14+05:30',
    author: AUTHOR_NAME,
    component: 'FasalBimaClaimStatusHindi',
    ogImage: '/og-image.webp',
  },
  {
    slug: 'hi/kisan-karj-mafi-list',
    titleHi: 'किसान कर्ज माफी 2026 — किस राज्य में सच में चल रही है',
    seoTitleHi: 'किसान कर्ज माफी 2026 — किस राज्य में चालू',
    desc: 'कोई राष्ट्रीय कर्ज माफी योजना नहीं है। महाराष्ट्र, तेलंगाना, UP और तमिलनाडु की असली स्थिति, official पोर्टल, फर्जी लिस्ट वाली साइटों का pattern और OTS जैसे 4 असली रास्ते।',
    keywords: [
      'किसान कर्ज माफी 2026',
      'कर्ज माफी लिस्ट कैसे देखें',
      'kisan karj mafi 2026 list',
      'महाराष्ट्र कर्जमाफी योजना 2026',
      'किसान ऋण मोचन योजना',
      'तेलंगाना रुणा माफी स्टेटस',
      'कर्ज माफी सच या झूठ',
      'KCC लोन माफ कैसे होता है',
    ],
    category: 'farming',
    publishedTime: '2026-08-18T07:42:14+05:30',
    modifiedTime: '2026-08-18T18:45:00+05:30',
    author: AUTHOR_NAME,
    component: 'KisanKarjMafiAllStatesHindi',
    ogImage: '/og-image.webp',
  },
  {
    slug: 'hi/pm-kisan-khad-yojana-sach',
    titleHi: 'PM किसान खाद योजना ₹11,000 — सच क्या है',
    seoTitleHi: 'PM किसान खाद योजना ₹11,000 का सच',
    desc: '₹11,000 वाली कोई अलग खाद योजना officially मौजूद नहीं है। अफवाह कहां से आई, खाद पर सरकार असल में क्या देती है और fake registration forms से कैसे बचें — पूरा सच यहां।',
    keywords: [
      'PM किसान खाद योजना',
      'pm kisan khad yojana 11000',
      'खाद योजना सच या झूठ',
      'fertilizer subsidy कैसे मिलती है',
      'यूरिया पर subsidy कितनी',
      'खाद योजना registration fraud',
    ],
    category: 'farming',
    publishedTime: '2026-08-18T11:30:00+05:30',
    modifiedTime: '2026-08-18T19:45:00+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisanKhadYojanaSachHindi',
    ogImage: '/og-image.webp',
  },
  {
    slug: 'hi/pm-kisan-helpline-155261',
    titleHi: 'PM किसान हेल्पलाइन 155261 — शिकायत कैसे और कहां करें',
    seoTitleHi: 'PM किसान हेल्पलाइन 155261 — शिकायत',
    desc: 'किस्त अटकी है? 155261 और 011-24300606 पर कब call करें, कौन सी problem कहां हल होगी — eKYC CSC पर, land seeding तहसील में — और शिकायत escalate का पूरा रास्ता।',
    keywords: [
      'PM किसान हेल्पलाइन नंबर',
      'pm kisan helpline 155261',
      'pm kisan complaint number',
      'पीएम किसान शिकायत कैसे करें',
      'pmkisan-ict@gov.in',
      'pm kisan toll free number',
    ],
    category: 'status-check',
    publishedTime: '2026-08-18T11:45:00+05:30',
    modifiedTime: '2026-08-18T18:30:00+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisanHelpline155261Hindi',
    ogImage: '/og-image.webp',
  },
];
