import { AUTHOR_NAME } from '@/lib/site-config';
import type { HindiArticle } from '@/lib/hindi-articles-data';

// PM Kisan yojana / status-check articles — Hindi (Devanagari) versions.
// Components live in components/articles/hindi-yojana/.
// URL structure unchanged: /articles/hi/<slug> (see lib/hindi-hreflang.ts for mapping).
export const HINDI_YOJANA_ARTICLES: readonly HindiArticle[] = [
  {
    slug: 'hi/pm-kisan-25vi-kist',
    titleHi: 'पीएम किसान 25वीं किस्त कब आएगी? Date और Latest Update',
    seoTitleHi: 'पीएम किसान 25वीं किस्त कब आएगी — Date Update',
    desc: 'किस्त की तारीख का इंतजार है? 25वीं किस्त की latest स्थिति, और वो तीन चीजें — eKYC, बैंक seeding, land seeding — जिनमें से एक भी अटकी हो तो पैसा रुक जाता है।',
    keywords: [
      'पीएम किसान 25वीं किस्त',
      'pm kisan 25th installment date',
      'पीएम किसान किस्त कब आएगी',
      'pm kisan kist kab aayegi 2027',
      'पीएम किसान किस्त नहीं आई क्या करें',
      'pm kisan beneficiary list me naam nahi hai',
      'pm kisan kist ka sms nahi aaya',
      'पीएम किसान किस्त ₹2000 कब बढ़ेगी',
      'pm kisan ekyc bank seeding land seeding check',
    ],
    category: 'status-check',
    publishedTime: '2026-07-27T20:05:06+05:30',
    modifiedTime: '2026-08-05T12:35:35+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisan25viKistKabAayegi',
    ogImage: '/images/articles/hindi-yojna/pm-kisan-25vi-kist/kisan-mobile-check.webp',
  },
  {
    slug: 'hi/status-check-mobile-se',
    titleHi: 'मोबाइल नंबर से पीएम किसान स्टेटस कैसे चेक करें? आसान तरीका',
    seoTitleHi: 'मोबाइल नंबर से पीएम किसान स्टेटस चेक करें',
    desc: 'पीएम किसान स्टेटस मोबाइल नंबर से 2 मिनट में चेक करें — रजिस्ट्रेशन नंबर भूल गए या OTP नहीं आ रहा? हर problem का आसान step-by-step solution यहां जानिए।',
    keywords: [
      'पीएम किसान स्टेटस चेक मोबाइल नंबर से',
      'pm kisan status mobile number',
      'pm kisan registration number kaise nikale',
      'पीएम किसान रजिस्ट्रेशन नंबर भूल गया',
      'pm kisan status otp nahi aa raha',
      'know your status pm kisan',
      'pm kisan ekyc status no',
      'पीएम किसान लैंड सीडिंग no',
      'aadhaar bank seeding no pm kisan',
    ],
    category: 'status-check',
    publishedTime: '2026-07-24T09:35:32+05:30',
    modifiedTime: '2026-08-07T14:31:10+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisanStatusCheckMobileNumberSe',
    ogImage: '/images/articles/hindi-yojna/status-check-mobile-se/phone-status-check.webp',
  },
  {
    slug: 'hi/helpline-shikayat',
    titleHi: 'किस्त नहीं आई? पीएम किसान हेल्पलाइन नंबर और शिकायत का तरीका',
    seoTitleHi: 'पीएम किसान हेल्पलाइन नंबर और शिकायत',
    desc: 'पीएम किसान की किस्त नहीं आई तो घबराएं नहीं — helpline number 155261 पर call करें या online complaint दर्ज करें। शिकायत का पूरा process यहां step-by-step जानिए।',
    keywords: ['पीएम किसान हेल्पलाइन नंबर', 'pm kisan complaint kaise kare'],
    category: 'status-check',
    publishedTime: '2026-04-08T14:18:51+05:30',
    modifiedTime: '2026-04-17T15:26:44+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisanHelplineNumberComplaint',
    ogImage: '/images/articles/hindi-yojna/helpline-shikayat/farmer-on-call.webp',
  },
  {
    slug: 'hi/nayi-registration',
    titleHi: 'पीएम किसान नई रजिस्ट्रेशन 2027 — Farmer ID से ऐसे करें Apply',
    seoTitleHi: 'पीएम किसान नई रजिस्ट्रेशन 2027 — Farmer ID',
    desc: 'पीएम किसान नई रजिस्ट्रेशन 2027 अब Farmer ID से होगी — online apply का step-by-step तरीका, जरूरी documents और आवेदन के बाद status चेक करना भी यहां सीखें।',
    keywords: ['पीएम किसान नई रजिस्ट्रेशन', 'pm kisan new registration 2027'],
    category: 'status-check',
    publishedTime: '2026-04-19T18:42:50+05:30',
    modifiedTime: '2026-04-24T08:39:57+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisanNewRegistration2027',
    ogImage: '/images/articles/hindi-yojna/new-registration/docs-ready.webp',
  },
  {
    slug: 'hi/farmer-id-kaise-banaye',
    titleHi: 'किसान आईडी (Farmer ID) कैसे बनाएं 2026? Documents और AgriStack Registration',
    seoTitleHi: 'किसान आईडी (Farmer ID) कैसे बनाएं 2026 — Documents List',
    desc: 'किसान आईडी (AgriStack Farmer ID) मोबाइल से 10 मिनट में बनाएं। जरूरी documents की पूरी list, राज्यवार portal links और step-by-step registration process यहां देखें।',
    keywords: ['किसान आईडी कैसे बनाएं', 'farmer id kaise banaye', 'agristack id kaise banaye', 'farmer id banane ke liye documents', 'किसान आईडी कार्ड', 'agristack farmer id'],
    category: 'farming',
    publishedTime: '2026-06-07T21:01:19+05:30',
    modifiedTime: '2026-06-21T13:03:34+05:30',
    author: AUTHOR_NAME,
    component: 'FarmerIdCardKaiseBanaye2027',
    ogImage: '/images/articles/hindi-yojna/farmer-id-card/id-card-sample.webp',
  },
  {
    slug: 'hi/ekyc-mobile-se',
    titleHi: 'PM Kisan eKYC मोबाइल से कैसे करें? OTP और Face Auth तरीका',
    seoTitleHi: 'PM Kisan eKYC मोबाइल से कैसे करें',
    desc: 'PM Kisan eKYC मोबाइल से free में करें — OTP और Face Auth App दोनों के आसान steps यहां। OTP नहीं आ रहा या record not found error? हर problem का fix भी।',
    keywords: [
      'पीएम किसान eKYC मोबाइल से',
      'pm kisan ekyc kaise kare',
      'face auth ekyc',
      'pm kisan ekyc otp nahi aa raha',
      'आधार में मोबाइल नंबर लिंक नहीं है ekyc',
      'pm kisan ekyc csc charges',
      'record not found with given aadhaar pm kisan',
      'ekyc already done matlab',
      'बुजुर्ग की ekyc face auth से कैसे करें',
    ],
    category: 'status-check',
    publishedTime: '2026-07-16T11:58:35+05:30',
    modifiedTime: '2026-07-21T11:55:34+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisanEkycMobileSeKaiseKare',
    ogImage: '/images/articles/hindi-yojna/ekyc-mobile-se/otp-screen.webp',
  },
  {
    slug: 'hi/npci-aadhaar-seeding',
    titleHi: 'NPCI आधार सीडिंग Online — DBT पेमेंट फिक्स',
    desc: 'NPCI आधार सीडिंग के बिना पीएम किसान की किस्त अटक सकती है — बैंक में aadhaar link status चेक करें और DBT enable करने का पूरा online process यहां जानिए।',
    keywords: ['npci aadhaar seeding online', 'dbt enable kaise kare', 'आधार बैंक लिंक स्टेटस'],
    category: 'status-check',
    publishedTime: '2026-07-19T18:38:27+05:30',
    modifiedTime: '2026-07-28T10:46:08+05:30',
    author: AUTHOR_NAME,
    component: 'NpciAadhaarSeedingDbtPayment',
    ogImage: '/images/articles/hindi-yojna/npci-seeding/seeding-diagram.webp',
  },
  {
    slug: 'hi/payment-stopped-by-state',
    titleHi: '"Payment Stopped by State" का मतलब क्या है? जानिए आसान Fix',
    seoTitleHi: 'Payment Stopped by State का मतलब और Fix',
    desc: 'PM Kisan status में "Payment Stopped by State" दिख रहा है? जानिए यह error क्यों आता है, कौन से documents check होते हैं और इसे ठीक करने का पूरा तरीका।',
    keywords: ['payment stopped by state pm kisan', 'pm kisan payment stopped fix'],
    category: 'status-check',
    publishedTime: '2026-05-02T08:41:15+05:30',
    modifiedTime: '2026-05-11T06:07:07+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisanPaymentStoppedByStateFix',
    ogImage: '/images/articles/hindi-yojna/payment-stopped/stopped-status.webp',
  },
  {
    slug: 'hi/recovery-notice',
    titleHi: 'PM Kisan Recovery Notice आया? पैसा वापस करने का पूरा तरीका',
    seoTitleHi: 'PM Kisan Recovery Notice — पैसा वापसी',
    desc: 'PM Kisan recovery notice आया है तो घबराएं नहीं — जानिए किन किसानों को पैसा वापस करना होगा, online refund का पूरा process और notice गलत हो तो क्या करें।',
    keywords: ['pm kisan recovery notice', 'pm kisan paisa wapas kaise kare'],
    category: 'status-check',
    publishedTime: '2026-04-26T14:26:28+05:30',
    modifiedTime: '2026-06-07T08:33:34+05:30',
    author: AUTHOR_NAME,
    component: 'PmKisanRecoveryNoticePaisaWapas',
    ogImage: '/images/articles/hindi-yojna/recovery-notice/notice-letter.webp',
  },
] as const;
