import { AUTHOR_NAME } from '@/lib/site-config';
import type { HindiArticle } from '@/lib/hindi-articles-data';

export const HINDI_RAJYA_YOJANA_ARTICLES: readonly HindiArticle[] = [
  {
    slug: 'hi/mp-kisan-kalyan-yojana',
    titleHi: 'MP किसान कल्याण योजना: ₹12000 सालाना कैसे मिलेंगे? जानिए',
    seoTitleHi: 'MP Kisan Kalyan Yojana: ₹12000 कैसे मिलेंगे?',
    desc: 'MP मुख्यमंत्री किसान कल्याण योजना से हर साल ₹12000 पाएं: kisan kalyan yojana status check, पात्रता और अगली किस्त की date की पूरी जानकारी हिंदी में देखें।',
    keywords: ['मुख्यमंत्री किसान कल्याण योजना', 'mp kisan kalyan yojana status', '₹12000 किसान योजना MP'],
    category: 'farming',
    publishedTime: '2026-08-09T00:42:08+03:00',
    modifiedTime: '2026-08-09T00:42:08+03:00',
    author: AUTHOR_NAME,
    component: 'MukhyamantriKisanKalyanYojanaMp',
    ogImage: '/images/articles/hindi-yojna/mp-kisan-kalyan/mp-farmer-field.webp',
  },
  {
    slug: 'hi/namo-shetkari-yojana',
    titleHi: 'नमो शेतकरी किस्त कब आएगी? पैसे का पूरा हिसाब जानिए',
    seoTitleHi: 'नमो शेतकरी किस्त कब आएगी: पैसे कब मिलेंगे',
    desc: 'नमो शेतकरी के पैसे कब आएंगे? किस्त का schedule PM Kisan से अलग है: nsmny.mahait.org पर status देखने का तरीका और पैसा अटके तो 4 fix यहां जानिए।',
    keywords: ['नमो शेतकरी योजना', 'namo shetkari yojana status', 'namo shetkari mahasanman nidhi', 'नमो शेतकरी महासन्मान निधी', 'namo shetkari yojana beneficiary list', 'namo shetkari ke paise kab aayenge'],
    category: 'farming',
    publishedTime: '2026-07-05T18:35:14+05:30',
    modifiedTime: '2026-07-21T19:40:24+05:30',
    author: AUTHOR_NAME,
    component: 'NamoShetkariYojanaMaharashtra',
    ogImage: '/images/articles/hindi-yojna/namo-shetkari/shetkari-field.webp',
  },
  {
    slug: 'hi/rajasthan-kisan-samman-nidhi',
    titleHi: 'राजस्थान किसान सम्मान निधि: ₹9,000 का हिसाब और किस्त की स्थिति',
    seoTitleHi: 'राजस्थान किसान सम्मान निधि: ₹9,000 किस्त',
    desc: 'राजस्थान के किसान को पीएम किसान के ₹6,000 के ऊपर राज्य से ₹3,000: कुल ₹9,000। जन आधार से किस्त देखने का तरीका और पैसा अटकने की वजहें।',
    keywords: [
      'राजस्थान किसान सम्मान निधि',
      'rajasthan kisan samman nidhi',
      'मुख्यमंत्री किसान सम्मान निधि राजस्थान',
      'mukhyamantri kisan samman nidhi rajasthan',
      'राजस्थान किसान सम्मान निधि किस्त स्थिति',
      'jan aadhaar se kisan samman nidhi status',
      'जन सूचना पोर्टल किसान सम्मान निधि',
      'rajasthan kisan samman nidhi 9000',
    ],
    category: 'farming',
    publishedTime: '2026-08-16T08:15:15+05:30',
    modifiedTime: '2026-08-17T23:59:45+05:30',
    author: AUTHOR_NAME,
    component: 'RajasthanKisanSammanNidhiHindi',
    ogImage: '/images/articles/rajya-yojna/rajasthan-kisan-samman-nidhi-9000/hero.webp',
  },
  {
    slug: 'hi/annadata-sukhibhava-status',
    titleHi: 'अन्नदाता सुखीभव स्थिति: ₹20,000 और CCRC का पूरा हिसाब',
    seoTitleHi: 'अन्नदाता सुखीभव स्थिति: ₹20,000 और CCRC कार्ड',
    desc: 'आंध्र प्रदेश की अन्नदाता सुखीभव से ₹20,000 सालाना: आधार से स्थिति देखने का तरीका, किस्तों का दर्ज हिसाब, और बटाईदार किसान के लिए CCRC कार्ड की पूरी बात।',
    keywords: [
      'अन्नदाता सुखीभव स्थिति',
      'annadata sukhibhava status check',
      'अन्नदाता सुखीभव ₹20000',
      'annadata sukhibhava beneficiary list',
      'ccrc card kya hai',
      'बटाईदार किसान अन्नदाता सुखीभव',
      'ysr rythu bharosa naya naam',
      'annadathasukhibhava ap gov in status',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T08:21:02+05:30',
    modifiedTime: '2026-08-20T10:13:58+05:30',
    author: AUTHOR_NAME,
    component: 'AnnadataSukhibhavaStatusHindi',
    ogImage: '/images/articles/rajya-yojna/annadata-sukhibhava-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/rythu-bharosa-status',
    titleHi: 'रायथु भरोसा स्थिति: बंधु से भरोसा तक, ₹12,000 प्रति एकड़ का हिसाब',
    seoTitleHi: 'रायथु भरोसा स्थिति: ₹12,000 प्रति एकड़',
    desc: 'तेलंगाना की रायथु भरोसा से ₹6,000 प्रति एकड़ हर मौसम: रायथु बंधु से असली फर्क, आधार से स्टेटस चेक और भू भारती रिकॉर्ड की रुकावटें।',
    keywords: [
      'रायथु भरोसा स्थिति',
      'rythu bharosa status check',
      'रायथु बंधु बनाम रायथु भरोसा',
      'rythu bharosa 12000 per acre',
      'rythu bharosa beneficiary list',
      'रायथु भरोसा किस्त कब आएगी',
      'rythu bharosa telangana kist',
      'भू भारती जमीन रिकॉर्ड तेलंगाना',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T16:35:15+05:30',
    modifiedTime: '2026-08-21T10:35:44+05:30',
    author: AUTHOR_NAME,
    component: 'RythuBharosaStatusHindi',
    ogImage: '/images/articles/rajya-yojna/rythu-bharosa-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/odisha-cm-kisan-status',
    titleHi: 'ओडिशा CM Kisan स्थिति: भूमिहीन को भी ₹12,500 का रास्ता',
    seoTitleHi: 'ओडिशा CM Kisan स्थिति: भूमिहीन को ₹12,500',
    desc: 'KALIA की जगह आई ओडिशा CM Kisan: आधार से स्टेटस चेक, जमीन वालों को ₹4,000 और भूमिहीन परिवार को ₹12,500 का हिसाब, और पैसा अटकने की आम वजहें।',
    keywords: [
      'ओडिशा सीएम किसान स्थिति',
      'odisha cm kisan status check',
      'cm kisan odisha भूमिहीन 12500',
      'cm kisan beneficiary list odisha',
      'kalia yojana नया नाम',
      'cmkisan odisha gov in status',
      'सीएम किसान योजना ओडिशा लिस्ट',
      'cm kisan village wise list',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T09:33:43+05:30',
    modifiedTime: '2026-08-21T01:54:45+05:30',
    author: AUTHOR_NAME,
    component: 'OdishaCmKisanStatusHindi',
    ogImage: '/images/articles/rajya-yojna/odisha-cm-kisan-status-check-2026/hero.webp',
  },
  {
    slug: 'hi/pati-patni-pm-kisan-rule',
    titleHi: 'पति-पत्नी दोनों को PM Kisan मिलेगा? नियम का सीधा जवाब',
    seoTitleHi: 'पति-पत्नी दोनों को PM Kisan मिलेगा?',
    desc: 'नहीं: एक परिवार (पति, पत्नी, नाबालिग बच्चे) में सिर्फ एक को PM Kisan मिलता है। गाइडलाइन का नियम, असली केस और गलत पंजीकरण सरेंडर करने का तरीका।',
    keywords: [
      'पति पत्नी दोनों को पीएम किसान',
      'pm kisan pati patni dono ko milega',
      'pm kisan family rule',
      'पीएम किसान एक परिवार एक लाभ',
      'pm kisan voluntary surrender kaise kare',
      'pm kisan recovery notice paisa wapas',
      'पीएम किसान पात्रता परिवार की परिभाषा',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T11:40:07+05:30',
    modifiedTime: '2026-08-21T08:49:32+05:30',
    author: AUTHOR_NAME,
    component: 'PatiPatniPmKisanRuleHindi',
    ogImage: '/images/articles/rajya-yojna/pm-kisan-pati-patni-dono-ko-milega/hero.webp',
  },
  {
    slug: 'hi/state-kisan-yojana-list',
    titleHi: 'राज्य किसान योजना लिस्ट 2026: किस राज्य में कितना पैसा मिलता है?',
    seoTitleHi: 'राज्य किसान योजना लिस्ट 2026: कितना पैसा',
    desc: 'PM Kisan के ₹6,000 के ऊपर आपका राज्य कितना देता है? MP, राजस्थान, महाराष्ट्र, AP, तेलंगाना, बंगाल, ओडिशा: हर राज्य की योजना, रकम और स्टेटस लिंक।',
    keywords: [
      'राज्य किसान योजना लिस्ट',
      'state kisan yojana list 2026',
      'किस राज्य में किसान को कितना पैसा मिलता है',
      'pm kisan ke upar state yojana',
      'मुख्यमंत्री किसान योजना सभी राज्य',
      'kisan yojana state wise amount',
      'राज्य सरकार किसान सहायता योजना',
    ],
    category: 'status-check',
    publishedTime: '2026-08-17T13:58:01+05:30',
    modifiedTime: '2026-08-21T23:14:50+05:30',
    author: AUTHOR_NAME,
    component: 'StateKisanYojanaListHindi',
    ogImage: '/images/articles/rajya-yojna/state-kisan-yojana-list-all-states-2026/hero.webp',
  },
  {
    slug: 'hi/parihara-payment-status',
    titleHi: 'परिहार पेमेंट स्टेटस 2026: फसल नुकसान मुआवजा कहां अटका, कैसे देखें?',
    seoTitleHi: 'परिहार पेमेंट स्टेटस 2026: फसल नुकसान मुआवजा',
    desc: 'कर्नाटक में फसल नुकसान (bele hani) का मुआवजा: parihara.karnataka.gov.in पर आधार या गांव की सूची से स्टेटस, SDRF दरें, FRUITS ID और अटके पैसे का हर रास्ता।',
    keywords: [
      'परिहार पेमेंट स्टेटस',
      'parihara payment status check',
      'फसल नुकसान मुआवजा कर्नाटक',
      'parihara karnataka gov in status',
      'बेले हानी मुआवजा स्टेटस',
      'FRUITS ID karnataka kisan',
      'फसल मुआवजा village wise list',
    ],
    category: 'status-check',
    publishedTime: '2026-08-16T22:46:07+05:30',
    modifiedTime: '2026-08-19T14:16:21+05:30',
    author: AUTHOR_NAME,
    component: 'PariharaPaymentStatusHindi',
    ogImage: '/images/articles/rajya-yojna/parihara-payment-status-check-2026/hero.webp',
  },
] as const;
