import type { ArticleMeta } from './categories';
import { AUTHOR_NAME, AUTHOR_BIO } from '@/lib/site-config';

export const LOAN_MANDI_PASHUPALAN_ARTICLES: readonly ArticleMeta[] = [
  {
    slug: 'dairy-farm-loan-without-collateral',
    ogImage: '/images/articles/loan-mandi-pashupalan/dairy-farm-loan-without-collateral/dairy-subah.webp',
    title: 'Dairy Farm Loan Bina Collateral 2026',
    desc: 'Zameen girvi rakhe bina dairy farm loan — Mudra se ₹20 lakh tak, PMEGP mein 15-35% subsidy, CGTMSE cover. EMI table, documents aur reject ki wajahein.',
    ogTitle: 'Dairy Farm Loan Bina Collateral — Mudra 2026',
    keywords: [
      'dairy farm loan without collateral 2026',
      'mudra loan dairy farming',
      'pmegp dairy subsidy',
      'cgtmse loan kisan',
      'bina zameen dairy loan',
      'dairy farm loan emi',
      'dairy loan documents',
      'pashupalan loan bina guarantee',
    ],
    component: 'DairyFarmLoanWithoutCollateral',
    category: 'loan',
    publishedTime: '2026-07-11T19:21:24+05:30',
    modifiedTime: '2026-08-01T08:27:01+05:30',
    readingTime: 11,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    schemes: ['mudra', 'pmegp', 'cgtmse'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanCreditCardOnlineApply2026', 'bakri-palan-yojana-nlm-subsidy'],
  },
  {
    slug: 'sbi-dairy-loan-interest-rate',
    ogImage: '/images/articles/loan-mandi-pashupalan/sbi-dairy-loan-interest-rate/subah-doodh.webp',
    title: 'SBI Dairy Loan Interest Rate 2026',
    desc: 'SBI dairy loan ka rate MCLR + spread se banta hai — koi fixed number nahi. KCC vs term loan ka fark, interest subvention, EMI table aur checklist.',
    ogTitle: 'SBI Kisan Dairy Loan 2026 — Rate, EMI, Apply',
    keywords: [
      'sbi dairy loan interest rate 2026',
      'sbi pashupalan loan',
      'sbi agri loan emi calculator',
      'kcc allied activities',
      'pashu kcc interest rate',
      'sbi dairy loan documents',
      'mclr agri loan rate',
      'interest subvention dairy loan',
    ],
    component: 'SbiDairyLoanInterestRate',
    category: 'loan',
    publishedTime: '2026-03-12T13:42:35+05:30',
    modifiedTime: '2026-03-21T08:13:49+05:30',
    readingTime: 11,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    banks: ['sbi'],
    schemes: ['kcc'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanCreditCardOnlineApply2026', 'dairy-farm-loan-without-collateral'],
  },
  {
    slug: 'jansamarth-portal-loan-apply',
    ogImage: '/images/articles/loan-mandi-pashupalan/jansamarth-portal-loan-apply/form-bharna.webp',
    title: 'JanSamarth Portal 2026: Loan Apply',
    desc: 'Ek portal par sabhi sarkari loan — KCC, Mudra, education, agri-infra. Eligibility check se application track tak, jansamarth.in ka poora step-by-step process.',
    ogTitle: 'JanSamarth Portal Loan Apply 2026 Guide',
    keywords: [
      'jansamarth portal loan apply 2026',
      'jansamarth kisan loan',
      'jansamarth eligibility check',
    ],
    component: 'JansamarthPortalLoanApply',
    category: 'loan',
    publishedTime: '2026-06-29T16:53:38+05:30',
    modifiedTime: '2026-07-04T08:32:11+05:30',
    readingTime: 10,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    schemes: ['kcc', 'mudra'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'dairy-farm-loan-without-collateral', 'KisanCreditCardOnlineApply2026'],
  },
  {
    slug: 'enam-registration-kaise-kare',
    ogImage: '/images/articles/loan-mandi-pashupalan/enam-registration-kaise-kare/anaj-dheri.webp',
    title: 'eNAM Registration 2026: Kaise Karein',
    desc: 'eNAM par free registration karke fasal online mandi mein bechein — 3 documents, step-by-step process, inter-state bidding aur bank payment.',
    ogTitle: 'eNAM Registration Kaise Kare 2026 Guide',
    keywords: [
      'enam registration kaise kare 2026',
      'enam portal farmer registration',
      'online mandi fasal bechna',
      'enam app kaise use kare',
      'enam inter state trade',
    ],
    component: 'EnamRegistrationKaiseKare',
    category: 'mandi',
    publishedTime: '2026-07-02T20:36:46+05:30',
    modifiedTime: '2026-07-16T16:28:23+05:30',
    readingTime: 11,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    schemes: ['enam'],
    relatedSlugs: ['mandi-bhav-today', 'msp-list-2026-27', 'mandi-bhav-app-comparison'],
  },
  {
    slug: 'msp-list-2026-27',
    title: 'MSP List 2026-27: Rabi & Kharif',
    desc: 'MSP list 2026-27 ki poori table — gehu ₹2,585, dhan ₹2,441, chana ₹5,875 aur baaki faslon ke rate, pichhle saal se comparison ke saath.',
    ogTitle: 'MSP List 2026-27 — Rabi & Kharif Puri List',
    ogImage: '/images/articles/loan-mandi-pashupalan/msp-list-2026-27/kharid-kendra.webp',
    keywords: [
      'msp list 2026 27',
      'gehu msp 2026',
      'dhan msp rate',
      'msp kya hai',
      'kharif msp 2026 27',
      'rabi msp 2026 27',
    ],
    component: 'MspList202627',
    category: 'mandi',
    publishedTime: '2026-05-30T15:19:53+05:30',
    modifiedTime: '2026-06-08T17:37:18+05:30',
    readingTime: 11,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    relatedSlugs: ['mandi-bhav-today', 'gehu-ka-bhav-msp-vs-mandi', 'enam-registration-kaise-kare'],
  },
  {
    slug: 'mandi-bhav-app-comparison',
    ogImage: '/images/articles/loan-mandi-pashupalan/mandi-bhav-app-comparison/phone-bhav.webp',
    title: 'Best Mandi Bhav Apps 2026: Top 7',
    desc: 'eNAM, AgMarknet, Kisan Suvidha ya private apps — kaunsa mandi bhav app sahi rate deta hai? Sarkari vs private comparison aur modal price ka matlab.',
    ogTitle: 'Best Mandi Bhav Apps 2026 — Top 7 Comparison',
    keywords: [
      'mandi bhav app 2026',
      'bijak app',
      'enam app',
      'aaj ka mandi rate app',
    ],
    component: 'MandiBhavAppComparison',
    category: 'mandi',
    publishedTime: '2026-03-07T07:06:57+05:30',
    modifiedTime: '2026-03-12T06:16:58+05:30',
    readingTime: 10,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    relatedSlugs: ['mandi-bhav-today', 'enam-registration-kaise-kare', 'msp-list-2026-27'],
  },
  {
    slug: 'gehu-ka-bhav-msp-vs-mandi',
    seoTitle: 'Gehu Ka Bhav 2026 — MSP vs Mandi Rate',
    ogImage: '/images/articles/loan-mandi-pashupalan/gehu-ka-bhav-msp-vs-mandi/gehu-katai.webp',
    title: 'Gehu Ka Bhav 2026: MSP vs Mandi Rate',
    desc: 'Gehu MSP ₹2,585 par bechein ya mandi mein? Seasonal price pattern, rok kar bechne ka ganit, storage tips aur poora decision framework.',
    ogTitle: 'Gehu Ka Bhav 2026 — MSP vs Mandi Rate, Kab Bechein',
    keywords: [
      'gehu ka bhav 2026',
      'wheat msp 2026',
      'gehu kab beche',
    ],
    component: 'GehuKaBhavMspVsMandi',
    category: 'mandi',
    publishedTime: '2026-05-26T11:51:46+05:30',
    modifiedTime: '2026-07-07T17:24:07+05:30',
    readingTime: 10,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    relatedSlugs: ['msp-list-2026-27', 'mandi-bhav-today', 'enam-registration-kaise-kare'],
  },
  {
    slug: 'sabzi-bhav-guide-pyaz-aloo-tamatar',
    ogImage: '/images/articles/loan-mandi-pashupalan/sabzi-bhav-guide-pyaz-aloo-tamatar/sabzi-mandi.webp',
    title: 'Pyaz-Aloo-Tamatar Bhav Guide 2026',
    desc: 'Pyaz, aloo, tamatar kab bechein? Teeno ka seasonal price cycle, aloo cold storage ka break-even hisaab aur NAFED buffer stock ka asar.',
    ogTitle: 'Pyaz, Aloo, Tamatar Kab Bechein — Bhav Cycle',
    keywords: [
      'pyaz ka bhav kab badhega',
      'aloo mandi rate',
      'tamatar bhav trend',
      'aloo cold storage kharcha',
      'pyaz kab bechna chahiye',
    ],
    component: 'SabziBhavGuidePyazAlooTamatar',
    category: 'mandi',
    publishedTime: '2026-03-28T16:58:58+05:30',
    modifiedTime: '2026-04-02T19:01:54+05:30',
    readingTime: 11,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    relatedSlugs: ['mandi-bhav-today', 'msp-list-2026-27', 'gehu-ka-bhav-msp-vs-mandi'],
  },
  {
    slug: 'murgi-palan-loan-nlm-subsidy',
    ogImage: '/images/articles/loan-mandi-pashupalan/murgi-palan-loan-nlm-subsidy/murgi-farm.webp',
    title: 'Murgi Palan Loan 2026: NLM 50% Subsidy',
    desc: 'NLM se poultry farm par 50% subsidy, ₹25 lakh tak — back-ended subsidy ka sach, layer vs broiler aur udyamimitra portal se apply ka process.',
    ogTitle: 'Murgi Palan Loan 2026 — NLM se 50% Subsidy',
    keywords: [
      'murgi palan loan 2026',
      'poultry farm subsidy',
      'nlm scheme poultry',
      'murgi farm kaise khole',
    ],
    component: 'MurgiPalanLoanNlmSubsidy',
    category: 'pashupalan',
    publishedTime: '2026-05-08T13:43:22+05:30',
    modifiedTime: '2026-05-29T15:56:37+05:30',
    readingTime: 11,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    schemes: ['nlm'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'dairy-farm-loan-without-collateral', 'pm-matsya-sampada-yojana-fish-farming'],
  },
  {
    slug: 'bihar-pashupalan-loan-yojana',
    seoTitle: 'Bihar Pashupalan Loan Yojana 2026: Subsidy',
    ogImage: '/images/articles/loan-mandi-pashupalan/bihar-pashupalan-loan-yojana/kisan-bhains.webp',
    title: 'Bihar Pashupalan Loan Yojana 2026',
    desc: 'Samagra Gavya Vikas Yojana — SC/ST ko 75%, General ko 50% subsidy tak. Eligibility, documents aur dairy.bihar.gov.in par apply ka process.',
    ogTitle: 'Bihar Pashupalan Loan Yojana 2026 — 50-75% Subsidy',
    keywords: [
      'bihar pashupalan loan yojana 2026',
      'samagra gavya vikas yojana',
      'dairy.bihar.gov.in apply',
    ],
    component: 'BiharPashupalanLoanYojana',
    category: 'pashupalan',
    publishedTime: '2026-05-20T14:31:32+05:30',
    modifiedTime: '2026-05-29T06:54:39+05:30',
    readingTime: 11,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    states: ['bihar'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'murgi-palan-loan-nlm-subsidy', 'dairy-farm-loan-without-collateral'],
  },
  {
    slug: 'rashtriya-gokul-mission-subsidy',
    ogImage: '/images/articles/loan-mandi-pashupalan/rashtriya-gokul-mission-subsidy/desi-gaay.webp',
    title: 'Rashtriya Gokul Mission 2026: Subsidy',
    desc: 'RGM se kisan ko kya milta hai — IVF pregnancy par ₹5,000, sex-sorted semen par 50% subsidy, muft AI aur Breed Multiplication Farm par ₹2 crore tak.',
    ogTitle: 'Rashtriya Gokul Mission — IVF ₹5,000 Subsidy',
    keywords: [
      'rashtriya gokul mission 2026',
      'desi gay palan subsidy',
      'sex sorted semen subsidy',
      'breed multiplication farm subsidy',
      'ivf pregnancy subsidy 5000',
    ],
    component: 'RashtriyaGokulMissionSubsidy',
    category: 'pashupalan',
    publishedTime: '2026-05-18T09:22:20+05:30',
    modifiedTime: '2026-05-23T16:51:28+05:30',
    readingTime: 11,
    author: AUTHOR_NAME,
    authorBio: AUTHOR_BIO,
    schemes: ['rgm'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'murgi-palan-loan-nlm-subsidy', 'bihar-pashupalan-loan-yojana'],
  },
] as const;
