import type { ArticleMeta } from './articles-data';

export const LOAN_MANDI_PASHUPALAN_ARTICLES: readonly ArticleMeta[] = [
  {
    slug: 'dairy-farm-loan-without-collateral',
    title: 'Dairy Farm Loan Bina Collateral 2026',
    desc: 'Zameen girvi rakhe bina dairy farm loan — Mudra se ₹20 lakh tak, PMEGP mein 15-35% subsidy, CGTMSE guarantee cover. EMI table, DPR ke heads, documents aur reject hone ki asli wajahein.',
    ogTitle: 'Dairy Farm Loan Bina Collateral 2026 — Mudra, PMEGP, CGTMSE',
    keywords: [
      'dairy farm loan without collateral 2026',
      'mudra loan dairy farming',
      'pmegp dairy subsidy',
      'cgtmse loan kisan',
      'bina zameen dairy loan',
      'dairy farm loan emi',
      'dairy loan documents',
      'pashupalan loan bina guarantee',
    ],
    component: 'DairyFarmLoanWithoutCollateral',
    category: 'loan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 11,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['mudra', 'pmegp', 'cgtmse'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanCreditCardOnlineApply2026', 'bakri-palan-yojana-nlm-subsidy'],
  },
  {
    slug: 'sbi-dairy-loan-interest-rate',
    title: 'SBI Dairy Loan Interest Rate 2026',
    desc: 'SBI dairy loan ka rate MCLR + spread se banta hai — koi fixed number nahi. KCC vs term loan ka fark, interest subvention, Scale of Finance, EMI table aur branch checklist.',
    ogTitle: 'SBI Kisan Dairy Loan 2026 — Rate, EMI, Apply',
    keywords: [
      'sbi dairy loan interest rate 2026',
      'sbi pashupalan loan',
      'sbi agri loan emi calculator',
      'kcc allied activities',
      'pashu kcc interest rate',
      'sbi dairy loan documents',
      'mclr agri loan rate',
      'interest subvention dairy loan',
    ],
    component: 'SbiDairyLoanInterestRate',
    category: 'loan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 11,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    banks: ['sbi'],
    schemes: ['kcc'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanCreditCardOnlineApply2026', 'dairy-farm-loan-without-collateral'],
  },
  {
    slug: 'jansamarth-portal-loan-apply',
    title: 'JanSamarth Portal 2026: Loan Apply',
    desc: 'Ek portal par sabhi sarkari loan — KCC, Mudra, education, agri-infra. Eligibility check se application track tak, jansamarth.in ka poora step-by-step process.',
    ogTitle: 'JanSamarth Portal Loan Apply 2026 Guide',
    keywords: [
      'jansamarth portal loan apply 2026',
      'jansamarth kisan loan',
      'jansamarth eligibility check',
    ],
    component: 'JansamarthPortalLoanApply',
    category: 'loan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 10,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['kcc', 'mudra'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'dairy-farm-loan-without-collateral', 'KisanCreditCardOnlineApply2026'],
  },
  {
    slug: 'enam-registration-kaise-kare',
    title: 'eNAM Registration 2026: Kaise Karein',
    desc: 'eNAM par free farmer registration karke fasal online mandi mein bechein — 3 documents, step-by-step process, bidding aur seedha bank payment.',
    ogTitle: 'eNAM Registration Kaise Kare 2026 Guide',
    keywords: [
      'enam registration kaise kare 2026',
      'enam portal farmer registration',
      'online mandi fasal bechna',
    ],
    component: 'EnamRegistrationKaiseKare',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 9,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['enam'],
    relatedSlugs: ['mandi-bhav-today', 'msp-list-2026-27', 'mandi-bhav-app-comparison'],
  },
  {
    slug: 'msp-list-2026-27',
    title: 'MSP List 2026-27: Rabi & Kharif',
    desc: 'MSP list 2026-27 ki poori table — gehu ₹2,585, dhan ₹2,441, chana ₹5,875 aur baaki faslon ke rate, pichhle saal se comparison ke saath. Rate kaise banta hai aur MSP par bechne ka process bhi.',
    ogTitle: 'MSP List 2026-27 — Rabi & Kharif Puri List',
    keywords: [
      'msp list 2026 27',
      'gehu msp 2026',
      'dhan msp rate',
      'msp kya hai',
      'kharif msp 2026 27',
      'rabi msp 2026 27',
    ],
    component: 'MspList202627',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 11,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    relatedSlugs: ['mandi-bhav-today', 'gehu-ka-bhav-msp-vs-mandi', 'enam-registration-kaise-kare'],
  },
  {
    slug: 'mandi-bhav-app-comparison',
    title: 'Best Mandi Bhav Apps 2026: Top 7',
    desc: 'eNAM, AgMarknet, Kisan Suvidha ya private apps — kaunsa mandi bhav app sahi rate deta hai? Sarkari vs private comparison, modal price ka matlab aur bina app ke raaste.',
    ogTitle: 'Best Mandi Bhav Apps 2026 — Top 7 Comparison',
    keywords: [
      'mandi bhav app 2026',
      'bijak app',
      'enam app',
      'aaj ka mandi rate app',
    ],
    component: 'MandiBhavAppComparison',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 10,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    relatedSlugs: ['mandi-bhav-today', 'enam-registration-kaise-kare', 'msp-list-2026-27'],
  },
  {
    slug: 'gehu-ka-bhav-msp-vs-mandi',
    title: 'Gehu Ka Bhav 2026: MSP vs Mandi Rate',
    desc: 'Gehu MSP ₹2,585 par bechein ya mandi mein? Seasonal price pattern, rok kar bechne ka ganit, storage tips aur bechne se pehle ke 4 sawaal — poora decision framework.',
    ogTitle: 'Gehu Ka Bhav 2026 — MSP vs Mandi Rate, Kab Bechein',
    keywords: [
      'gehu ka bhav 2026',
      'wheat msp 2026',
      'gehu kab beche',
    ],
    component: 'GehuKaBhavMspVsMandi',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 10,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    relatedSlugs: ['msp-list-2026-27', 'mandi-bhav-today', 'enam-registration-kaise-kare'],
  },
  {
    slug: 'sabzi-bhav-guide-pyaz-aloo-tamatar',
    title: 'Pyaz-Aloo-Tamatar Bhav Guide 2026',
    desc: 'Sabzi kab bechein zyada rate par? Pyaz, aloo aur tamatar ka seasonal price cycle, cold storage aur NAFED. Guide jald aa rahi hai.',
    ogTitle: 'Pyaz-Aloo-Tamatar Bhav Guide — Kab Bechein',
    keywords: [
      'pyaz ka bhav kab badhega',
      'aloo mandi rate',
      'tamatar bhav trend',
    ],
    component: 'SabziBhavGuidePyazAlooTamatar',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    relatedSlugs: ['mandi-bhav-today', 'msp-list-2026-27', 'gehu-ka-bhav-msp-vs-mandi'],
  },
  {
    slug: 'murgi-palan-loan-nlm-subsidy',
    title: 'Murgi Palan Loan 2026: NLM 50% Subsidy',
    desc: 'NLM se poultry farm par 50% subsidy, ₹25 lakh tak — back-ended subsidy ka sach, layer vs broiler, udyamimitra portal se apply ka poora process aur 5 common galtiyan.',
    ogTitle: 'Murgi Palan Loan & Subsidy 2026 — NLM se 50% Tak',
    keywords: [
      'murgi palan loan 2026',
      'poultry farm subsidy',
      'nlm scheme poultry',
      'murgi farm kaise khole',
    ],
    component: 'MurgiPalanLoanNlmSubsidy',
    category: 'pashupalan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 11,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['nlm'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'dairy-farm-loan-without-collateral', 'pm-matsya-sampada-yojana-fish-farming'],
  },
  {
    slug: 'bihar-pashupalan-loan-yojana',
    title: 'Bihar Pashupalan Loan Yojana 2026',
    desc: 'Samagra Gavya Vikas Yojana — SC/ST ko 75%, General ko 50% subsidy tak. Eligibility, documents, dairy.bihar.gov.in par apply ka poora process aur 7 common galtiyan.',
    ogTitle: 'Bihar Pashupalan Loan Yojana 2026 — 50-75% Subsidy',
    keywords: [
      'bihar pashupalan loan yojana 2026',
      'samagra gavya vikas yojana',
      'dairy.bihar.gov.in apply',
    ],
    component: 'BiharPashupalanLoanYojana',
    category: 'pashupalan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 11,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    states: ['bihar'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'murgi-palan-loan-nlm-subsidy', 'dairy-farm-loan-without-collateral'],
  },
  {
    slug: 'rashtriya-gokul-mission-subsidy',
    title: 'Rashtriya Gokul Mission 2026: Subsidy',
    desc: 'RGM se kisan ko kya milta hai — IVF pregnancy par ₹5,000, sex-sorted semen par 50% subsidy, muft AI, aur Breed Multiplication Farm par ₹2 crore tak. Poora process aur 4 galatfehmiyan.',
    ogTitle: 'Rashtriya Gokul Mission 2026 — IVF ₹5,000, Semen 50%, Farm ₹2 Cr',
    keywords: [
      'rashtriya gokul mission 2026',
      'desi gay palan subsidy',
      'sex sorted semen subsidy',
      'breed multiplication farm subsidy',
      'ivf pregnancy subsidy 5000',
    ],
    component: 'RashtriyaGokulMissionSubsidy',
    category: 'pashupalan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 11,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['rgm'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'murgi-palan-loan-nlm-subsidy', 'bihar-pashupalan-loan-yojana'],
  },
] as const;
