import type { ArticleMeta } from './articles-data';

// 11 new articles from the low-competition content plan (Aug 2026).
// Separate from the core list in articles-data.ts; categories are shared.
export const LOW_COMPETITION_ARTICLES: readonly ArticleMeta[] = [
  {
    slug: 'dairy-farm-loan-without-collateral',
    title: 'Dairy Farm Loan Bina Collateral 2026',
    desc: 'Bina zameen ya property girvi rakhe dairy farm loan — Mudra, PMEGP aur CGTMSE se ₹20 lakh tak. Puri guide jald aa rahi hai.',
    ogTitle: 'Dairy Farm Loan Bina Collateral 2026 — Mudra, PMEGP, CGTMSE',
    keywords: [
      'dairy farm loan without collateral 2026',
      'mudra loan dairy farming',
      'pmegp dairy subsidy',
      'cgtmse loan kisan',
    ],
    component: 'DairyFarmLoanWithoutCollateral',
    category: 'loan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['mudra', 'pmegp', 'cgtmse'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanCreditCardOnlineApply2026', 'bakri-palan-yojana-nlm-subsidy'],
  },
  {
    slug: 'sbi-dairy-loan-interest-rate',
    title: 'SBI Dairy Loan Interest Rate 2026',
    desc: 'SBI se dairy aur allied activities loan — interest rate, EMI tables aur YONO se apply karne ka process. Puri guide jald aa rahi hai.',
    ogTitle: 'SBI Kisan Dairy Loan 2026 — Rate, EMI, Apply',
    keywords: [
      'sbi dairy loan interest rate 2026',
      'sbi pashupalan loan',
      'sbi agri loan emi calculator',
      'kcc allied activities',
    ],
    component: 'SbiDairyLoanInterestRate',
    category: 'loan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    banks: ['sbi'],
    schemes: ['kcc'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'KisanCreditCardOnlineApply2026', 'dairy-farm-loan-without-collateral'],
  },
  {
    slug: 'jansamarth-portal-loan-apply',
    title: 'JanSamarth Portal 2026: Loan Apply',
    desc: 'Ek portal par sabhi sarkari loan — KCC, Mudra, education, agri-infra. JanSamarth se apply karne ki step-by-step guide jald aa rahi hai.',
    ogTitle: 'JanSamarth Portal Loan Apply 2026 Guide',
    keywords: [
      'jansamarth portal loan apply 2026',
      'jansamarth kisan loan',
      'jansamarth eligibility check',
    ],
    component: 'JansamarthPortalLoanApply',
    category: 'loan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['kcc', 'mudra'],
    relatedSlugs: ['KisanRinKahaSeLe2026', 'dairy-farm-loan-without-collateral', 'KisanCreditCardOnlineApply2026'],
  },
  {
    slug: 'enam-registration-kaise-kare',
    title: 'eNAM Registration 2026: Kaise Karein',
    desc: 'eNAM par free farmer registration karke fasal online mandi mein bechein — 3 documents, step-by-step process, bidding aur seedha bank payment.',
    ogTitle: 'eNAM Registration Kaise Kare 2026 Guide',
    keywords: [
      'enam registration kaise kare 2026',
      'enam portal farmer registration',
      'online mandi fasal bechna',
    ],
    component: 'EnamRegistrationKaiseKare',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 9,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['enam'],
    relatedSlugs: ['mandi-bhav-today', 'msp-list-2026-27', 'mandi-bhav-app-comparison'],
  },
  {
    slug: 'msp-list-2026-27',
    title: 'MSP List 2026-27: Rabi & Kharif',
    desc: 'Saari faslon ki MSP list 2026-27 — gehu, dhan aur baaki crops ke rate, pichle saal se comparison. Puri table jald aa rahi hai.',
    ogTitle: 'MSP List 2026-27 — Rabi & Kharif Puri List',
    keywords: [
      'msp list 2026 27',
      'gehu msp 2026',
      'dhan msp rate',
      'msp kya hai',
    ],
    component: 'MspList202627',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    relatedSlugs: ['mandi-bhav-today', 'gehu-ka-bhav-msp-vs-mandi', 'enam-registration-kaise-kare'],
  },
  {
    slug: 'mandi-bhav-app-comparison',
    title: 'Best Mandi Bhav Apps 2026: Top 7',
    desc: 'eNAM, Bijak, Kisan Suvidha, AgMarknet — kaunsa app sabse sahi mandi rate deta hai? Comparison jald aa raha hai.',
    ogTitle: 'Best Mandi Bhav Apps 2026 — Top 7 Comparison',
    keywords: [
      'mandi bhav app 2026',
      'bijak app',
      'enam app',
      'aaj ka mandi rate app',
    ],
    component: 'MandiBhavAppComparison',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    relatedSlugs: ['mandi-bhav-today', 'enam-registration-kaise-kare', 'msp-list-2026-27'],
  },
  {
    slug: 'gehu-ka-bhav-msp-vs-mandi',
    title: 'Gehu Ka Bhav 2026: MSP vs Mandi Rate',
    desc: 'Gehu MSP par bechein ya open market mein? Seasonal trend, storage tips aur kab bechna sahi hai. Puri guide jald aa rahi hai.',
    ogTitle: 'Gehu Ka Bhav 2026 — MSP vs Mandi Rate, Kab Bechein',
    keywords: [
      'gehu ka bhav 2026',
      'wheat msp 2026',
      'gehu kab beche',
    ],
    component: 'GehuKaBhavMspVsMandi',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    relatedSlugs: ['msp-list-2026-27', 'mandi-bhav-today', 'enam-registration-kaise-kare'],
  },
  {
    slug: 'sabzi-bhav-guide-pyaz-aloo-tamatar',
    title: 'Pyaz-Aloo-Tamatar Bhav Guide 2026',
    desc: 'Sabzi kab bechein zyada rate par? Pyaz, aloo aur tamatar ka seasonal price cycle, cold storage aur NAFED. Guide jald aa rahi hai.',
    ogTitle: 'Pyaz-Aloo-Tamatar Bhav Guide — Kab Bechein',
    keywords: [
      'pyaz ka bhav kab badhega',
      'aloo mandi rate',
      'tamatar bhav trend',
    ],
    component: 'SabziBhavGuidePyazAlooTamatar',
    category: 'mandi',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    relatedSlugs: ['mandi-bhav-today', 'msp-list-2026-27', 'gehu-ka-bhav-msp-vs-mandi'],
  },
  {
    slug: 'murgi-palan-loan-nlm-subsidy',
    title: 'Murgi Palan Loan 2026: NLM 50% Subsidy',
    desc: 'NLM se poultry farm par 50% tak subsidy — layer vs broiler cost, loan process aur apply steps. Puri guide jald aa rahi hai.',
    ogTitle: 'Murgi Palan Loan & Subsidy 2026 — NLM se 50% Tak',
    keywords: [
      'murgi palan loan 2026',
      'poultry farm subsidy',
      'nlm scheme poultry',
      'murgi farm kaise khole',
    ],
    component: 'MurgiPalanLoanNlmSubsidy',
    category: 'pashupalan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['nlm'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'dairy-farm-loan-without-collateral', 'pm-matsya-sampada-yojana-fish-farming'],
  },
  {
    slug: 'bihar-pashupalan-loan-yojana',
    title: 'Bihar Pashupalan Loan Yojana 2026',
    desc: 'Samagra Gavya Vikas Yojana — SC/ST ko 75%, General ko 50% subsidy, ₹2-10 lakh tak. Apply process jald aa raha hai.',
    ogTitle: 'Bihar Pashupalan Loan Yojana 2026 — 50-75% Subsidy',
    keywords: [
      'bihar pashupalan loan yojana 2026',
      'samagra gavya vikas yojana',
      'dairy.bihar.gov.in apply',
    ],
    component: 'BiharPashupalanLoanYojana',
    category: 'pashupalan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    states: ['bihar'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'murgi-palan-loan-nlm-subsidy', 'dairy-farm-loan-without-collateral'],
  },
  {
    slug: 'rashtriya-gokul-mission-subsidy',
    title: 'Rashtriya Gokul Mission 2026: Subsidy',
    desc: 'Desi gay palan par subsidy — breed improvement, IVF aur sex-sorted semen ke fayde, apply process. Puri guide jald aa rahi hai.',
    ogTitle: 'Rashtriya Gokul Mission 2026 — Desi Gay Palan Subsidy',
    keywords: [
      'rashtriya gokul mission 2026',
      'desi gay palan subsidy',
      'gokul gram yojana',
    ],
    component: 'RashtriyaGokulMissionSubsidy',
    category: 'pashupalan',
    publishedTime: '2026-08-05T08:00:00+05:30',
    modifiedTime: '2026-08-05T08:00:00+05:30',
    readingTime: 6,
    author: 'KisanStatus Editorial Team',
    authorBio: 'Agricultural content experts with 5+ years experience in government scheme research',
    schemes: ['rgm'],
    relatedSlugs: ['bakri-palan-yojana-nlm-subsidy', 'murgi-palan-loan-nlm-subsidy', 'bihar-pashupalan-loan-yojana'],
  },
] as const;
