export type MaandhanArticleMeta = {
  slug: string;
  title: string;
  description: string;
  category: string;
  published: string;
  modified: string;
  readTime: string;
  image?: string;
  ogImage?: string;
};

export const MAANDHAN_ARTICLES: MaandhanArticleMeta[] = [
  {
    slug: 'pm-kisan-maandhan-registration-2026',
    title: 'PM Kisan Maandhan Registration 2026',
    description: 'PM Kisan Maandhan Yojana mein online registration ka complete process, eligibility, aur zaroori documents ki jankari.',
    category: 'pension-scheme',
    published: '2026-07-21T08:00:00+05:30',
    modified: '2026-07-25T08:00:00+05:30',
    readTime: '12 min read',
    image: '/images/articles/maandhan/registration-hero.webp',
    ogImage: '/images/articles/maandhan/registration-hero.webp',
  },
  {
    slug: 'pm-kisan-maandhan-eligibility-documents',
    title: 'PM Kisan Maandhan Eligibility & Documents',
    description: 'Janie kaun se kisan is pension scheme ke liye eligible hain aur registration ke waqt kaun se documents zaroori hain.',
    category: 'pension-scheme',
    published: '2026-07-21T08:00:00+05:30',
    modified: '2026-07-25T08:00:00+05:30',
    readTime: '10 min read',
    image: '/images/articles/maandhan/eligibility-check-farmer-documents.webp',
    ogImage: '/images/articles/maandhan/eligibility-check-farmer-documents.webp',
  },
  {
    slug: 'pm-kisan-maandhan-pension-calculator',
    title: 'PM Kisan Maandhan Pension Calculator 2026',
    description: 'Complete pension calculator guide. 18 se 40 saal ki umar ke beech join karne par monthly contribution aur ₹3000 pension ka hisaab.',
    category: 'pension-scheme',
    published: '2026-07-21T08:00:00+05:30',
    modified: '2026-07-25T08:00:00+05:30',
    readTime: '8 min read',
    image: '/images/articles/maandhan/pension-calculator-hero.webp',
    ogImage: '/images/articles/maandhan/pension-calculator-hero.webp',
  },
  {
    slug: 'pm-kisan-maandhan-withdrawal-refund-rules',
    title: 'PM Kisan Maandhan Withdrawal & Refund Rules',
    description: 'PM Kisan Maandhan se exit karne ke rules, pension ka paisa family ko kaise milega, aur contribution refund hone ki puri sachai.',
    category: 'pension-scheme',
    published: '2026-07-21T08:00:00+05:30',
    modified: '2026-07-25T08:00:00+05:30',
    readTime: '9 min read',
    image: '/images/articles/maandhan/withdrawal-decision-hero.webp',
    ogImage: '/images/articles/maandhan/withdrawal-decision-hero.webp',
  },
  {
    slug: 'pm-kisan-maandhan-auto-debit-poora-sach',
    title: 'PM Kisan Maandhan Auto-Debit: Poora Sach',
    description: 'PM Kisan ke ₹2000 mein se ₹55-200 kyun kat rahe hain? NACH auto-debit mandate, CSC pe sign kiya gaya form, aur contribution pay karne ka asli process samjhiye.',
    category: 'pension-scheme',
    published: '2026-07-24T08:00:00+05:30',
    modified: '2026-07-25T08:00:00+05:30',
    readTime: '11 min read',
    image: '/images/articles/maandhan/auto-debit-confusion-hero.webp',
    ogImage: '/images/articles/maandhan/auto-debit-confusion-hero.webp',
  },
  {
    slug: 'pm-kisan-maandhan-status-check-online',
    title: 'PM Kisan Maandhan Status Check Online',
    description: 'PM Kisan Maandhan Yojana mein apna status kaise verify kijiye. Pension card download, passbook check, contribution history aur missed payment ka pura process.',
    category: 'pension-scheme',
    published: '2026-07-24T08:00:00+05:30',
    modified: '2026-07-25T08:00:00+05:30',
    readTime: '10 min read',
    image: '/images/articles/maandhan/status-check-portal-hero.webp',
    ogImage: '/images/articles/maandhan/status-check-portal-hero.webp',
  },
  {
    slug: 'pm-kisan-maandhan-pension-card-download',
    title: 'PM Kisan Maandhan Pension Card Download',
    description: 'PMKMY pension card ya acknowledgement slip ghar baithe online kaise download karein. CSC, bank branch, aur common problems ka complete solution.',
    category: 'pension-scheme',
    published: '2026-07-25T08:00:00+05:30',
    modified: '2026-07-28T08:00:00+05:30',
    readTime: '10 min read',
    image: '/images/articles/maandhan/pension-card-download-hero.webp',
    ogImage: '/images/articles/maandhan/pension-card-download-hero.webp',
  },
  {
    slug: 'family-pension-rules',
    title: 'PM Kisan Maandhan Family Pension Rules',
    description: 'PMKMY account holder ke dehant ke baad spouse ko pension kaise milegi, nomination rules, aur family pension claim karne ka pura process.',
    category: 'pension-scheme',
    published: '2026-07-26T08:00:00+05:30',
    modified: '2026-07-28T08:00:00+05:30',
    readTime: '9 min read',
    image: '/images/articles/maandhan/family-pension-rules/hero.webp',
    ogImage: '/images/articles/maandhan/family-pension-rules/hero.webp',
  },
  {
    slug: 'pmkmy-bank-account-change',
    title: 'PMKMY Bank Account Change Process',
    description: 'PM Kisan Maandhan Yojana me registered bank account kaise badlein ya update karein. Documents, application format, aur common problems ka hal.',
    category: 'pension-scheme',
    published: '2026-07-27T08:00:00+05:30',
    modified: '2026-07-28T08:00:00+05:30',
    readTime: '11 min read',
    image: '/images/articles/maandhan/bank-account-change/hero.webp',
    ogImage: '/images/articles/maandhan/bank-account-change/hero.webp',
  },
  {
    slug: 'pmkmy-grievance-complaint-helpline',
    title: 'PMKMY Grievance & Complaint Helpline',
    description: 'PM Kisan Maandhan Yojana me shikayat kaise karein? Helpline numbers, online grievance process, CSC complaint, aur common problems ka practical solution.',
    category: 'pension-scheme',
    published: '2026-07-28T08:00:00+05:30',
    modified: '2026-07-28T08:00:00+05:30',
    readTime: '12 min read',
    image: '/images/articles/maandhan/pmkmy-grievance-complaint-helpline/pmkmy-grievance-complaint-helpline-hero.webp',
    ogImage: '/images/articles/maandhan/pmkmy-grievance-complaint-helpline/pmkmy-grievance-complaint-helpline-hero.webp',
  },
  {
    slug: 'auto-debit-fail-hone-par-regularization-kaise-karein',
    title: 'Auto Debit Fail Hone Par Regularization Kaise Karein',
    description: 'EMI ya SIP auto-debit fail ho gaya? Janiye ise turant regularize karne ka aasan tarika, bank charges bachane ke upay aur CIBIL score safe rakhne ke tips.',
    category: 'pension-scheme',
    published: '2026-07-29T08:00:00+05:30',
    modified: '2026-07-29T08:00:00+05:30',
    readTime: '10 min read',
    image: '/images/articles/maandhan/auto-debit-fail-hone-par-regularization-kaise-karein/kisan-emi-tension.webp',
    ogImage: '/images/articles/maandhan/auto-debit-fail-hone-par-regularization-kaise-karein/kisan-emi-tension.webp',
  },
  {
    slug: 'pm-kisan-maandhan-age-wise-contribution-chart-2026',
    title: 'PM Kisan Maandhan Yojana: Age-Wise Monthly Contribution Chart 2026',
    description: 'PM-KMY mein 18 se 40 saal tak har umar ka exact monthly contribution, government co-contribution, registration process, aur pension rules — official sources se verify karke.',
    category: 'pension-scheme',
    published: '2026-07-30T10:00:00+05:30',
    modified: '2026-07-30T18:00:00+05:30',
    readTime: '12 min read',
    image: '/images/articles/maandhan/MaandhanContributionGuide/hero.webp',
    ogImage: '/images/articles/maandhan/MaandhanContributionGuide/hero.webp',
  },
];