export type RajyaArticleStatus = 'planned' | 'live';

export type RajyaYojanaArticleMeta = {
  slug: string;
  mainKeyword: string;
  readonly secondaryKeywords: readonly string[];
  title: string;
  description: string;
  ogTitle: string;
  component: string;
  state: string;
  officialPortal: string;
  status: RajyaArticleStatus;
  published: string;
  modified: string;
  readTime: string;
  ogImage?: string;
  readonly relatedPaths: readonly string[];
};

export const RAJYA_YOJANA_ARTICLES: readonly RajyaYojanaArticleMeta[] = [
  {
    slug: 'rajasthan-kisan-samman-nidhi-9000',
    mainKeyword: 'rajasthan kisan samman nidhi 9000',
    secondaryKeywords: [
      'cm kisan samman nidhi rajasthan 7 kist kab aayegi 2026',
      'rajasthan kisan samman nidhi status check',
      'rajasthan kisan samman nidhi kist kab aayegi',
      'rajasthan kisan nidhi badhi',
      'rajasthan kisan samman nidhi kist',
      'mukhyamantri kisan samman nidhi rajasthan',
    ],
    title: 'Rajasthan Kisan Samman Nidhi — Kist Kab Aayegi 2026',
    description:
      'Rajasthan Kisan Samman Nidhi: 6vi kist pending hai, 7vi kist uske baad aayegi — official date abhi announce nahi. Jan Soochna se status check, eligibility aur badhi raqam ka sach yahan.',
    ogTitle: 'Rajasthan Kisan Samman Nidhi — Nayi Raqam Aur Status',
    component: 'RajasthanKisanSammanNidhi9000',
    state: 'Rajasthan',
    officialPortal: '',
    status: 'live',
    published: '2026-06-09T14:52:57+05:30',
    modified: '2026-06-18T14:07:55+05:30',
    readTime: '10 min read',
    ogImage: '/images/articles/rajya-yojna/rajasthan-kisan-samman-nidhi-9000/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisan24viKist2026'],
  },
  {
    slug: 'annadata-sukhibhava-status-check-2026',
    mainKeyword: 'annadata sukhibhava status check',
    secondaryKeywords: [
      'annadata sukhibhava payment status',
      'annadata sukhibhava eligibility',
      'annadata sukhibhava beneficiary list',
      'ysr rythu bharosa new name',
      'annadata sukhibhava installment date',
      'ccrc ap gov in',
      'ccrc cards ap gov in login',
      'ccrc card status check',
    ],
    title: 'Annadata Sukhibhava Status Check 2026',
    description:
      'Andhra Pradesh Annadata Sukhibhava scheme ka status check, eligibility, tenant farmer CCRC rules aur payment ki poori jaankari.',
    ogTitle: 'Annadata Sukhibhava Status Check — AP Kisan Yojana',
    component: 'AnnadataSukhibhavaStatusCheck',
    state: 'Andhra Pradesh',
    officialPortal: 'https://annadathasukhibhava.ap.gov.in',
    status: 'live',
    published: '2026-06-11T10:16:36+05:30',
    modified: '2026-07-23T08:11:27+05:30',
    readTime: '11 min read',
    ogImage: '/images/articles/rajya-yojna/annadata-sukhibhava-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanBeneficiaryList2026'],
  },
  {
    slug: 'mp-kisan-kalyan-yojana-kist-status',
    mainKeyword: 'cm kisan kalyan yojana kist kab aayegi',
    secondaryKeywords: [
      'mp kisan kalyan yojana status',
      'kisan kalyan yojana mp status',
      'mp saara payment status',
      'cm kisan beneficiary status mp saara',
      'cm saara',
      'mp kisan kalyan yojana status check',
      'saara portal kisan kalyan status',
      'kisan kalyan yojana beneficiary list mp',
      'mp kisan kalyan yojana amount',
    ],
    title: 'MP Kisan Kalyan Yojana Kist Status',
    description:
      'Saal ke ₹12,000 mein se aapki kist kahan atki hai — SAARA portal par status kholne ka step, list mein naam dhoondhna, aur late hone par kya karna hai.',
    ogTitle: 'MP Kisan Kalyan Yojana — Kist Aur Status Check',
    component: 'MpKisanKalyanYojanaKist',
    state: 'Madhya Pradesh',
    officialPortal: 'https://saara.mp.gov.in',
    status: 'live',
    published: '2026-06-13T15:46:30+05:30',
    modified: '2026-07-04T18:16:19+05:30',
    readTime: '10 min read',
    ogImage: '/images/articles/rajya-yojna/mp-kisan-kalyan-yojana-kist-status/hero.webp',
    relatedPaths: ['/articles/PmKisan24viKist2026', '/articles/PmKisanPaymentFailedFix2026'],
  },
  {
    slug: 'namo-shetkari-yojana-status-check-2026',
    mainKeyword: 'namo shetkari yojana status check',
    secondaryKeywords: [
      'namo shetkari hapta kadhi milel',
      'namo shetkari status',
      'namo kisan status check',
      'namo shetkari yojana beneficiary list 2026 pdf',
      'namo shetkari 9 instalment',
      'namo shetkari beneficiary list',
      'namo shetkari yojana registration',
      'pm kisan aaya namo shetkari nahi aaya',
      'नमो शेतकरी महासन्मान निधी',
    ],
    title: 'Namo Shetkari Status 2026 — Beneficiary List',
    description:
      'PM Kisan ka paisa aa gaya par Namo Shetkari ka hapta nahi? Maharashtra ki beneficiary list mein naam check karein, aur ye samjhein ki dono alag kyun aate hain.',
    ogTitle: 'Namo Shetkari Yojana — Status Aur Hapta Check',
    component: 'NamoShetkariYojanaStatus',
    state: 'Maharashtra',
    officialPortal: 'https://nsmny.mahait.org',
    status: 'live',
    published: '2026-06-15T18:27:56+05:30',
    modified: '2026-06-24T11:34:06+05:30',
    readTime: '11 min read',
    ogImage: '/images/articles/rajya-yojna/namo-shetkari-yojana-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanPaymentFailedFix2026', '/articles/PmKisanBeneficiaryList2026'],
  },
  {
    slug: 'rythu-bharosa-status-check-2026',
    mainKeyword: 'rythu bharosa status check',
    secondaryKeywords: [
      'rythu bharosa',
      'rythu bharosa status check',
      'rythu bandhu list',
      'rythu bharosa payment status',
      'rythu bharosa per acre amount',
      'rythu bharosa phase wise payment',
      'rythu bandhu vs rythu bharosa',
    ],
    title: 'Rythu Bharosa Status Check 2026',
    description:
      'Rythu Bharosa: ₹12,000 per acre per saal (₹6,000 Kharif + ₹6,000 Rabi) — Telangana kisano ko DBT se. Status check steps, phase-wise payment aur Rythu Bandhu se farak yahan.',
    ogTitle: 'Rythu Bharosa Status Check — Telangana Kisan Yojana',
    component: 'RythuBharosaStatusCheck',
    state: 'Telangana',
    officialPortal: '',
    status: 'live',
    published: '2026-06-17T19:59:40+05:30',
    modified: '2026-07-17T19:41:31+05:30',
    readTime: '11 min read',
    ogImage: '/images/articles/rajya-yojna/rythu-bharosa-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanBeneficiaryList2026'],
  },
  {
    slug: 'krishak-bandhu-status-check-2026',
    mainKeyword: 'krishak bandhu status check',
    secondaryKeywords: [
      'krishak bandhu status check voter id',
      'krishak bandhu verification list',
      'krishak bandhu voter id se status',
      'krishak bandhu death benefit',
      'krishak bandhu payment date',
      'কৃষক বন্ধু status',
    ],
    title: 'Krishak Bandhu Status Check 2026',
    description:
      'West Bengal Krishak Bandhu ka status Voter ID se kaise check karein, verification list, death benefit aur payment ki jaankari.',
    ogTitle: 'Krishak Bandhu Status Check — Voter ID Se',
    component: 'KrishakBandhuStatusCheck',
    state: 'West Bengal',
    officialPortal: 'https://krishakbandhu.wb.gov.in',
    status: 'live',
    published: '2026-06-20T10:03:34+05:30',
    modified: '2026-08-01T10:16:33+05:30',
    readTime: '10 min read',
    ogImage: '/images/articles/rajya-yojna/krishak-bandhu-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanCorrectionForm2026'],
  },
  {
    slug: 'odisha-cm-kisan-status-check-2026',
    mainKeyword: 'cm kisan odisha status check',
    secondaryKeywords: [
      'kalia list',
      'odisha cm kisan status check',
      'cm kisan portal odisha status check 2026 list village wise',
      'cm kisan beneficiary list odisha',
      'kalia yojana new name',
      'cm kisan odisha landless farmer benefit',
      'cmkisan odisha gov in status',
    ],
    title: 'Odisha CM Kisan Status Check 2026',
    description:
      'Naam list mein hai par paisa nahi aaya? CM Kisan portal par status dekhne ka tareeka, cultivator aur landless ki alag list, aur e-KYC ka pech.',
    ogTitle: 'Odisha CM Kisan Status Check — KALIA Ka Naya Naam',
    component: 'OdishaCmKisanStatusCheck',
    state: 'Odisha',
    officialPortal: 'https://cmkisan.odisha.gov.in',
    status: 'live',
    published: '2026-06-23T11:42:30+05:30',
    modified: '2026-07-02T13:07:23+05:30',
    readTime: '10 min read',
    ogImage: '/images/articles/rajya-yojna/odisha-cm-kisan-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanBeneficiaryList2026'],
  },
  {
    slug: 'pm-kisan-pati-patni-dono-ko-milega',
    mainKeyword: 'pati patni dono ko pm kisan milega ya nahi',
    secondaryKeywords: [
      'pm kisan family rules',
      'ek parivar mein kitne logo ko pm kisan',
      'pm kisan exclusion list',
      'pm kisan kaun eligible nahi hai',
      'pm kisan galat paisa wapas kaise karein',
    ],
    title: 'Pati Patni Dono Ko PM Kisan Milega?',
    description:
      'PM Kisan mein ek parivar ka rule, pati-patni dono ko paisa milta hai ya nahi, poori exclusion list aur galat mila paisa wapas karne ka process.',
    ogTitle: 'Pati Patni Dono Ko PM Kisan? — Family Rule',
    component: 'PmKisanPatiPatniRule',
    state: 'ALL',
    officialPortal: 'https://pmkisan.gov.in',
    status: 'live',
    published: '2026-06-25T11:03:57+05:30',
    modified: '2026-06-30T21:35:04+05:30',
    readTime: '9 min read',
    ogImage: '/images/articles/rajya-yojna/pm-kisan-pati-patni-dono-ko-milega/hero.webp',
    relatedPaths: [
      '/articles/PmKisanVoluntarySurrenderGuide',
      '/articles/PmKisanRejectedStatusReApplyGuide',
    ],
  },
  {
    slug: 'state-kisan-yojana-list-all-states-2026',
    mainKeyword: 'state kisan yojana list',
    secondaryKeywords: [
      'kis state mein kitna paisa milta hai kisan ko',
      'pm kisan plus state scheme',
      'rajya kisan samman nidhi list',
      'state wise farmer scheme amount',
    ],
    title: 'State Kisan Yojana List 2026 — Sabhi Rajya',
    description:
      'Har state ki kisan income-support yojana ek jagah — scheme ka naam, raqam, official portal aur status check link ke saath.',
    ogTitle: 'State Kisan Yojana List — Kis Rajya Mein Kitna',
    component: 'StateKisanYojanaHub',
    state: 'ALL',
    officialPortal: '',
    status: 'live',
    published: '2026-06-27T21:55:32+05:30',
    modified: '2026-08-08T11:42:33+05:30',
    readTime: '12 min read',
    ogImage: '/images/articles/rajya-yojna/state-kisan-yojana-list-all-states-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026'],
  },
  {
    slug: 'krishak-unnati-yojana-status-check-2026',
    mainKeyword: 'krishak unnati yojana status check',
    secondaryKeywords: [
      'krishak unnati yojana payment status',
      'krishak unnati yojana antar rashi',
      'cg dhan bonus 3100 status',
      'krishak unnati yojana 15000 per acre',
    ],
    title: 'Krishak Unnati Yojana Status Check 2026',
    description:
      'Chhattisgarh Krishak Unnati Yojana antar rashi ka status, ₹3,100 prati quintal ka hisaab, ekmusht payment aur Kharif 2026 se naya ₹15,000 prati acre component.',
    ogTitle: 'Krishak Unnati Yojana — Antar Rashi Aur Naya ₹15,000 Component',
    component: 'KrishakUnnatiYojanaStatusCheck',
    state: 'Chhattisgarh',
    officialPortal: 'https://khadya.cg.nic.in',
    status: 'live',
    published: '2026-07-07T14:52:37+05:30',
    modified: '2026-07-16T14:14:52+05:30',
    readTime: '11 min read',
    ogImage: '/images/articles/rajya-yojna/krishak-unnati-yojana-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisan24viKist2026'],
  },
  {
    slug: 'meri-fasal-mera-byora-status-check-2026',
    mainKeyword: 'meri fasal mera byora status check',
    secondaryKeywords: [
      'meri fasal mera byora registration',
      'fasal haryana gov in status',
      'meri fasal mera byora last date',
      'e kharid gate pass haryana',
      'mfmb status check family id',
      'meri fasal mera byora payment status',
    ],
    title: 'Meri Fasal Mera Byora Status Check 2026',
    description:
      'Meri Fasal Mera Byora status 5 minute me check karein — mobile, family ID ya CSC se. Rejected entry ka fix aur MSP payment atakne ke 4 karan bhi.',
    ogTitle: 'Meri Fasal Mera Byora Status — Registration Se MSP Tak',
    component: 'MeriFasalMeraByoraStatusCheck2026',
    state: 'Haryana',
    officialPortal: 'https://fasal.haryana.gov.in',
    status: 'live',
    published: '2026-07-31T08:34:02+05:30',
    modified: '2026-08-06T19:43:49+05:30',
    readTime: '12 min read',
    ogImage: '/images/articles/rajya-yojna/meri-fasal-mera-byora-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanPaymentFailedFix2026'],
  },
  {
    slug: 'bihar-kisan-registration-status-check-2026',
    mainKeyword: 'dbt agriculture bihar status check',
    secondaryKeywords: [
      'bihar kisan registration status check',
      'dbt agriculture bihar gov in registration',
      'kisan panjikaran sankhya bihar',
      'diesel anudan status check bihar',
      'krishi input anudan status',
      'bihar kisan registration number kaise nikale',
    ],
    title: 'DBT Agriculture Bihar Status Check 2026',
    description:
      'DBT Agriculture Bihar par registration number se anudan status check karein — diesel, krishi input, beej anudan aur kho gaya number nikalne ka poora raasta.',
    ogTitle: 'DBT Agriculture Bihar — Registration Aur Anudan Status',
    component: 'BiharKisanRegistrationStatusCheck2026',
    state: 'Bihar',
    officialPortal: 'https://dbtagriculture.bihar.gov.in',
    status: 'live',
    published: '2026-08-09T13:16:17+05:30',
    modified: '2026-08-11T12:36:56+05:30',
    readTime: '13 min read',
    ogImage: '/images/articles/rajya-yojna/bihar-kisan-registration-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanPaymentFailedFix2026'],
  },
  {
    slug: 'parihara-payment-status-check-2026',
    mainKeyword: 'parihara payment status check',
    secondaryKeywords: [
      'parihara payment status village wise',
      'bele parihara list 2026',
      'parihara karnataka gov in',
      'parihara status check aadhaar number',
      'bele hani parihara payment',
      'fruits id parihara status',
    ],
    title: 'Parihara Payment Status 2026 Village Wise',
    description:
      'Parihara payment status Aadhaar se ya village wise list se check karein — naam na hone, pending ya bank me paisa na aane par har branch ka fix yahan hai.',
    ogTitle: 'Parihara Payment Status — Village Wise List Aur Fix',
    component: 'PariharaPaymentStatusCheck2026',
    state: 'Karnataka',
    officialPortal: 'https://parihara.karnataka.gov.in',
    status: 'live',
    published: '2026-08-06T08:23:14+05:30',
    modified: '2026-08-08T19:59:50+05:30',
    readTime: '12 min read',
    ogImage: '/images/articles/rajya-yojna/parihara-payment-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanPaymentFailedFix2026'],
  },
  {
    slug: 'up-kisan-karj-rahat-list-2026',
    mainKeyword: 'up kisan karj rahat list',
    secondaryKeywords: [
      'up kisan karj rahat status check',
      'kisan rin mochan yojana list',
      'up karj mafi list 2026',
      'upkisankarjrahat upsdc gov in',
      'kisan karj rahat shikayat status',
      'up kisan karj mafi eligibility',
    ],
    title: 'UP Kisan Karj Rahat List 2026 — Status',
    description:
      'UP Kisan Karj Rahat list me apna naam check karein, asli portal pehchaniye aur naam na hone par shikayat darj karne ka poora process jaaniye.',
    ogTitle: 'UP Kisan Karj Rahat List — Naam Check Aur Shikayat',
    component: 'UpKisanKarjRahatList2026',
    state: 'Uttar Pradesh',
    officialPortal: 'https://upkisankarjrahat.upsdc.gov.in',
    status: 'live',
    published: '2026-08-02T20:46:54+05:30',
    modified: '2026-08-06T09:01:07+05:30',
    readTime: '12 min read',
    ogImage: '/images/articles/rajya-yojna/up-kisan-karj-rahat-list-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanPaymentFailedFix2026'],
  },
  {
    slug: 'ikhedut-portal-status-check-2026',
    mainKeyword: 'ikhedut portal status check',
    secondaryKeywords: [
      'ikhedut arji status check',
      'ikhedut portal yojana list 2026',
      'ikhedut gujarat gov in login',
      'tractor sahay yojana status gujarat',
      'ikhedut subsidy status check',
      'ikhedut arji number kaise nikale',
    ],
    title: 'iKhedut Portal Status Check 2026 — Arji Status',
    description:
      'iKhedut portal par arji status check karein, yojana list ki window dekhein aur reject hone ke 6 karan samjhein — subsidy ka stage-wise poora hisaab.',
    ogTitle: 'iKhedut Portal Status Check — Arji Se Subsidy Tak',
    component: 'IkhedutPortalStatusCheck2026',
    state: 'Gujarat',
    officialPortal: 'https://ikhedut.gujarat.gov.in',
    status: 'live',
    published: '2026-08-11T10:23:13+05:30',
    modified: '2026-08-11T16:32:56+05:30',
    readTime: '14 min read',
    ogImage: '/images/articles/rajya-yojna/ikhedut-portal-status-check-2026/hero.webp',
    relatedPaths: ['/articles/PmKisanMasterGuide2026', '/articles/PmKisanPaymentFailedFix2026'],
  },
];

export const LIVE_RAJYA_YOJANA_ARTICLES: readonly RajyaYojanaArticleMeta[] =
  RAJYA_YOJANA_ARTICLES.filter((a) => a.status === 'live');

export function getRajyaYojanaArticle(slug: string): RajyaYojanaArticleMeta | undefined {
  return RAJYA_YOJANA_ARTICLES.find((a) => a.slug === slug);
}

export const INSTALMENT_TRACKER_PAGE = {
  path: '/articles/PmKisan24viKist2026',
  mainKeyword: 'pm kisan 24vi kist kab aayegi',
  secondaryKeywords: [
    'pm kisan 24vi kist status check',
    'pm kisan kist list 2026',
    'pm kisan next installment date',
  ],
  note:
    'Naya article na banayein. Kist release hone ke din hi "Latest Update" box update karein, ' +
    'release se pehle sirf "expected" likhein, aur us din is cluster ke state articles ko link karein.',
} as const;
