{
  slug: 'pm-kisan-self-registered-status-check',
  title: 'PM Kisan Self Registration Status Check 2026: Khud Kiya Registration? Yahan Se Pata Karo',
  desc: 'Khud online registration kiya? Status check kaise karein? Step-by-step guide with screenshots.',
  ogTitle: 'PM Kisan Self Registration Status — Complete Guide',
  keywords: ['pm kisan self registration status', 'khud registration status check', 'online registration kaise check kare'],
  component: 'PmKisanSelfRegisteredStatusCheck',
  category: 'status-check',
  publishedTime: '2026-03-20T08:00:00+05:30',
  modifiedTime: '2026-07-06T08:00:00+05:30',
  readingTime: 10,
  schemes: ['pm-kisan'],
  ogImage: '/images/articles/pm-kisan-self-registered-status-check.webp',
  relatedSlugs: ['PmKisan24viKist2026', 'PmKisanMasterGuide2026', 'PmKisanEkycOnline2026'],
},